### ISSUE TITLE
Question: SQS DeleteMessageBatch

### ISSUE THREAD

**Issue by simplepath** [pplu/aws-sdk-perl#101]
I have referenced your page on SQS (https://github.com/pplu/aws-sdk-perl/blob/master/examples/sqs.pl) and am having trouble with a command for DeleteMessageBatch.

I have tried:
DeleteMessageBatch(QueueUrl => $base_q_url,ReceiptHandle => @array)

My use is that I am going to get 1-10 via ReceiveMessage and would like to determine the right way to send back to SQS to delete these messages.  

Thank you for Paws!
Derek

**Comment by pplu** [comment]
Hi,

  DeleteMessageBatch has other parameters (documented here: https://metacpan.org/pod/Paws::SQS#DeleteMessageBatch-Entries-ArrayRef-Paws::SQS::DeleteMessageBatchRequestEntry-QueueUrl-Str)

  So the call to DeleteMessageBatch looks like:
```
$sqs->DeleteMessageBatch(QueueUrl => $q, Entries => [
  { Id => $id1, ReceiptHandle => $rh1 },
  { Id => $id2, ReceiptHandle => $rh2 },
  ...
]);
```

**Comment by simplepath** [comment]
Thank you.  That's exactly what I needed to see.

Again, I really appreciate your work to create Paws.
