### ISSUE TITLE
S3 response headers mapped incorrectly

### ISSUE THREAD

**Issue by glenveegee** [pplu/aws-sdk-perl#116]
The Paws::API::Caller::response_to_object sub is given a $unserialized_struct object that contains a mix of keys - partly from parsing the response body and partly from the response header. 

The mappings from the response header are converted from standard lowercase headers to Mixed case Key that "should" match the attributes of the response object attributes

This is done on line 38 of Paws::Net::RestXMLResponse::handle_response sub

 `38:     my $object_attribute = join('', map{ ucfirst $_ } split(/-/, $key));`

This works most of the time converting headers like `content-length` to `ContentLength`

If the response object being built has a ContentLength attribute then this will be extracted and built from the $unserialized_struct object

Unfortunately this will not work for headers such as `etag` which is often used in S3

`$s3->UploadPart()` Should return an object that contains the ETag that was created but when the response header is converted it becomes Etag (note the difference in case). It therefore follows that the ETag attribute of `Paws::S3::UploadPartOutput`  will never be set (and in this case it's necessary to complete multipart uploads)

A proposed solution (I've tested it and it works) would be to modify line 38 above to always lowercase response headers and then look for exact matches or lowercase matched in the $unserialized_struct object

Paws::Net::RestXMLResponse::handle_response looks like this

`38:     my $object_attribute = join('', map{ lc($_) } split(/-/, $key));`

and then Paws::API::Caller::new_from_struct (line 133)

`133:     my $value = $result->{ $key };`

is changed to 

`133:     my $value = $result->{ $key } || $result->{ lc($key) };`

Sorry about the line numbers as I know they'll change but it's not exactly easy to describe this bug.

...and it is a bug.

**Comment by glenveegee** [comment]
I think this can actually be addressed by fixing the Paws::API::Builder::restxml::callresult_class_template  so this can probably be closed (see https://github.com/pplu/aws-sdk-perl/issues/117)

**Comment by pplu** [comment]
Closed, as we are treating this on #117.
