### ISSUE TITLE
Paws::API::Builder::restxml::callresult_class_template is faulty

### ISSUE THREAD

**Issue by glenveegee** [pplu/aws-sdk-perl#117]
<pre>
has callresult_class_template => (is => 'ro', isa => 'Str', default => q#
[%- operation = c.result_for_operation(op_name) %]
[%- shape = c.result_for_operation(op_name) %]
[%- op_name = c.shapename_for_operation_output(op_name) %]
[%- IF (shape) %]
package [% c.api %]::[% op_name %];
  use Moose;
[% FOREACH param_name IN shape.members.keys.sort -%]
  [%- member = c.shape(shape.members.$param_name.shape) -%]
  has [% param_name %] => (is => 'ro', isa => '[% member.perl_type %]'
  [%- IF (member.member.locationName) %], traits => ['Unwrapped'], xmlname => '[% member.member.locationName %]'[% END %]
  [%- IF (member.locationName) %], traits => ['Unwrapped'], xmlname => '[% member.locationName %]'[% END %]
  [%- IF (shape.members.$param_name.streaming == 1) %], traits => ['ParamInBody'][% stream_param = param_name %][% END %]
  [%- IF (c.required_in_shape(shape,param_name)) %], required => 1[% END %]);
[% END %]
  [%- IF (stream_param) -%]
  use MooseX::ClassAttribute;
  class_has _stream_param => (is => 'ro', default => '[% stream_param %]');
  [%- END -%]
[%- END %]
1;
[% c.class_documentation_template | eval %]
#);
</pre>

Doesn't correctly extract and configure locationName.

It should be 

<pre>
has callresult_class_template => (is => 'ro', isa => 'Str', default => q#
[%- operation = c.result_for_operation(op_name) %]
[%- shape = c.result_for_operation(op_name) %]
[%- op_name = c.shapename_for_operation_output(op_name) %]
[%- IF (shape) %]
package [% c.api %]::[% op_name %];
  use Moose;
[% FOREACH param_name IN shape.members.keys.sort -%]
  [%- member = c.shape(shape.members.$param_name.shape) -%]
  has [% param_name %] => (is => 'ro', isa => '[% member.perl_type %]'
  [%- IF (shape.members.$param_name.locationName) %]
    [%- IF (shape.members.$param_name.location == 'header') %], traits => ['ParamInHeader'], header_name => '[% shape.members.$param_name.locationName -%]'
    [%- ELSIF (shape.members.$param_name.location == 'querystring') %], traits => ['ParamInQuery'], query_name => '[% shape.members.$param_name.locationName -%]' 
    [%- ELSIF (shape.members.$param_name.location == 'uri') %], traits => ['ParamInURI'], uri_name => '[% shape.members.$param_name.locationName -%]' 
    [%- ELSE %], traits => ['Unwrapped'], xmlname => '[% shape.members.$param_name.locationName %]'[%- END -%][%- END -%]
  [%- IF (shape.members.$param_name.streaming == 1) %], traits => ['ParamInBody'][% stream_param = param_name %][% END %]
  [%- IF (c.required_in_shape(shape,param_name)) %], required => 1[% END %]);
[% END %]
  [%- IF (stream_param) -%]
  use MooseX::ClassAttribute;
  class_has _stream_param => (is => 'ro', default => '[% stream_param %]');
  [%- END -%]
[%- END %]
1;
[% c.class_documentation_template | eval %]
#);
</pre>

and then we can finally do something sensible when generating responses. We might even be able to do away with the response header to object attribute mapping

**Comment by pplu** [comment]
It looks right on spot! I've applied this on a branch so we can work on it: https://github.com/pplu/aws-sdk-perl/tree/feat/s3_support
