### ISSUE TITLE
AutoScaling Activity DataType 

### ISSUE THREAD

**Issue by raelga** [pplu/aws-sdk-perl#129]
Hello!

Some scaling activities didn't have a Cause defined although is a required element accordingly to the API documentation. 

```
 Cause

    The reason the activity began.
    Type: String
    Length Constraints: Minimum length of 1. Maximum length of 1023.
    Pattern: [\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\r\n\t]*
    Required: Yes
```

For example:

```
        {
            "Description": "Updating load balancers/target groups: Successful.  Status Reason: Added: foo (Load Balancer), bar (Load Balancer).",
            "AutoScalingGroupName": "fooASG",
            "ActivityId": "123456",
            "Details": "{}",
            "StartTime": "2016-10-27T14:12:03.830Z",
            "Progress": 100,
            "EndTime": "2016-10-27T14:12:07Z",
            "Cause": "",
            "StatusMessage": "Added: foo (Load Balancer), bar (Load Balancer).",
            "StatusCode": "Successful"
        },
```

So when Paws tries to create an object of type `Activity` with empty Cause attribute, for example calling `DescribeScalingActivities`, fails due to `Attribute (Cause) is required` :

```
package Paws::AutoScaling::Activity;
  use Moose;
  has ActivityId => (is => 'ro', isa => 'Str', required => 1);
  has AutoScalingGroupName => (is => 'ro', isa => 'Str', required => 1);
  has Cause => (is => 'ro', isa => 'Str', required => 1);
  has Description => (is => 'ro', isa => 'Str');
  has Details => (is => 'ro', isa => 'Str');
  has EndTime => (is => 'ro', isa => 'Str');
  has Progress => (is => 'ro', isa => 'Int');
  has StartTime => (is => 'ro', isa => 'Str', required => 1);
  has StatusCode => (is => 'ro', isa => 'Str', required => 1);
  has StatusMessage => (is => 'ro', isa => 'Str');
1;
```

Updating the Cause attribute to non-required solves the issue.

**Comment by pplu** [comment]
In the example that you send, it looks like Cause is an empty string (and Paws should be OK with that in a required field).

Can you generate a test case with

`paws_make_testcase AutoScaling --region xxx ...`

Please remember to scrub any confidential data from the file that gets generated

**Comment by raelga** [comment]
This can be closed, was reported again 2 years later and fixed at [Error on DescribeScalingActivities when Cause is empty #224](https://github.com/pplu/aws-sdk-perl/issues/22).
