### ISSUE TITLE
S3 GetObject will remove CR or LF at end of file

### ISSUE THREAD

**Issue by orbweaver** [pplu/aws-sdk-perl#130]
We have uploaded some encrypted files to S3, one has 0D at the end.  Another file has 0A.  When I download with S3 GetObject, those bytes are missing from the end of those files, and decryption fails.  How do I get GetObjectResponse to treat the Body as raw binary data?

**Comment by pplu** [comment]
Can you show me the code of how you download the file and decrypt it? I'm puzzled why GetObject should munge those characters off the end of the string

**Comment by orbweaver** [comment]
I'm using the "Body" param in the Response and putting it into a scalar.  I'm not sure if this is the best way to do it, but it's the first thing tried. Thanks for taking a look. 

my $s3 = Paws->service('S3', region => 'us-west-2');
my $res = $s3->GetObject(
                Bucket => $bucket,
                Key => $file,
                );

my $buffer = $res->{'Body'};

print "saving to $file\n";
open (OUTFILE, "> $file") or die $!;
binmode OUTFILE;
print OUTFILE $buffer;
close OUTFILE;

**Comment by pplu** [comment]
Bug found and squatted! I've patched it in this way. It hasn't broken any tests, but I want to give it another look before applying it.

```
diff --git a/lib/Paws/API/Caller.pm b/lib/Paws/API/Caller.pm
index 9719d52..370971b 100644
--- a/lib/Paws/API/Caller.pm
+++ b/lib/Paws/API/Caller.pm
@@ -2,7 +2,6 @@ package Paws::API::Caller;
   use Moose::Role;
   use Carp;
   use Paws::Net::APIRequest;
-  use String::Util qw/trim/;
 
   has caller => (is => 'ro', required => 1);
 
@@ -209,7 +208,7 @@ package Paws::API::Caller;
                 $args{ $att } = 0;
               }
             } else {
-              $args{ $att } = trim($value);
+              $args{ $att } = $value;
             }
           }
         }
```

**Comment by orbweaver** [comment]
Fantastic!  Thanks for fixing that.
