### ISSUE TITLE
Paws::SNS::TopicAttributesMap Map defined as HashRef[Str], but values may be undef

### ISSUE THREAD

**Issue by Grinnz** [pplu/aws-sdk-perl#135]
In a call to $sns->GetTopicAttributes, which returns an object containing an Attributes parameter of class Paws::SNS::TopicAttributesMap, an attribute (in our case DisplayName) can be null, leading to the `HashRef[Str]` type check to fail. This should probably be `HashRef[Maybe[Str]]`.

    Paws::SNS::TopicAttributesMap->new(Map => { DisplayName => undef });

    Attribute (Map) does not pass the type constraint because: Validation failed for 'HashRef[Str]' with value HASH(0x11eae98)

**Comment by pplu** [comment]
Hi,

  This just got solved and pushed to CPAN (v 0.29)

**Comment by Grinnz** [comment]
Thanks!
