### ISSUE TITLE
Undeclared test dependencies

### ISSUE THREAD

**Issue by Grinnz** [pplu/aws-sdk-perl#138]
The test file 99_pod_syntax.t requires Test::Pod, but this is not declared as a test dependency. Also, pod tests should really only be run author side and not on installation. To do this you can add a line like this before loading Test::Pod:

use if !$ENV{AUTHOR_TESTING}, 'Test::More', skip_all => 'author testing only';

And you can set AUTHOR_TESTING=1 in .travis.yml. (dzil test will also set it)

Another issue, 11_client_exceptions.t loads Paws::Net::FurlCaller and Paws::Net::LWPCaller regardless of whether Furl or LWP are installed, so the test dies when they aren't. It looks like it used to skip the test if they were not installed but this logic was removed: https://github.com/pplu/aws-sdk-perl/commit/ab6f4b9ea095077945bf50a5a3bdf547929ac888#diff-ace018b2440c2394b2534639530bfec8L17

**Comment by pplu** [comment]
This will be pushed to CPAN very soon
