### ISSUE TITLE
RunInstances(DryRun => 1 ...) Creates Instance and not doing DryRun

### ISSUE THREAD

**Issue by Eduard3000** [pplu/aws-sdk-perl#141]
Hi Fellows,

EC2 Service Method RunInstances used with DryRun => 1 does create the Instance instead of verifiying credentials&permissions ....

Would be nice if somebody fix, or tell how to do right.

Regards,
Eduard

**Comment by pplu** [comment]
Hi!

Bug caught, squashed and tested so it won't happen again. In ce499043561e71d8b7d808ec81ba0c6d81dee3a6 you can find the fix. Basically, Boolean values were not being transmitted correctly to the API

**Comment by Eduard3000** [comment]
Hola Jose,

for making this Module and fixing this.

Muchas gracias! :+1: :clap: :smiley:

Regards,
Eduard

**Comment by Eduard3000** [comment]
Forgot to verify: Patched my Paws 0.30 with git diff and worxx: 
Request would have succeeded, but DryRun flag is set.
:+1: :clap:

Saludos,
Eduard

**Comment by pplu** [comment]
I've just pushed Paws 0.31 with this change to CPAN
