### ISSUE TITLE
Q: How to pass a string variable to RunInstances(BlockDeviceMappings => $bdmdef...)

### ISSUE THREAD

**Issue by Eduard3000** [pplu/aws-sdk-perl#142]
Hi Fellows,

when I try to pass a string variable to the BlockDeviceMappings Attribute of the RunInstances Method
it complains about not expecting a string. Im a bit lost how to do this right, please advice.

(I dynamically create the BDM definition string with the VolumeSizes before, according to a csv table)

Regards,
Eduard

**Comment by pplu** [comment]
Can you paste the piece of code where you are invoking RunInstances?

It should have to be something like:

Without looking at your code, I suppose you're trying to pass a string to BlockDeviceMappings like this:
```
$ec2->RunInstances(
   ...
   BlockDeviceMappings => $string_with_bdms
)
```

What Paws would expect is something like this
```
$ec2->RunInstances(
   ...
   BlockDeviceMappings => [
      { DeviceName => '...', Ebs => { VolumeSize => $size, VolumeType => '..', ... }
   ],
   ...
);
```
The keys/values you can put in each position of the BlockDeviceMappings array are here: https://metacpan.org/pod/Paws::EC2::BlockDeviceMapping
and the keys/values you can put in the Ebs hash is here:
https://metacpan.org/pod/Paws::EC2::EbsBlockDevice

Hope it helps :)

**Comment by Eduard3000** [comment]
Hola Jose,
thanks for the quick reply first.

I will have diffrent ebs device count, thus is there no way of passing a $string_with_bdmsdefinition, or an BDM Object with the predefined mapping to the RunInstances method?!

With the plain way my device count is fixed...!? :expressionless:

Regards,
Eduard

**Comment by pplu** [comment]
You can use formulas like:
```
foreach $machine (...) {
  my $dbm = [];
  foreach my $volume (...) {
    push @$bdm, { DeviceName => '...', Ebs => { VolumeSize => $size, VolumeType => '..', ... }
  }
  ...
  $ec2->RunInstances(
    ...
    BlockDeviceMappings => $bdm,
    ...
  );
}
```
to make the the $bdm variable per machine.
Just pass BlockDeviceMappings an ArrayRef of Hashes with the appropiate block device mapping information ;)

**Comment by Eduard3000** [comment]
Hola Jose,

you have a little typo $dbm/bdm in your example, but then you reminded me of the magic eval function,
which does the trick, but now I get:

Attribute (VolumeSize) does not pass the type constraint because: Validation failed for 'Int' with value undef at /usr/local/lib/x86_64-linux-gnu/perl/5.22.1/Moose/Object.pm line 24

Even though I checked my $bdm, did it your way and my way with eval, always above exception... 😑

Please try on your own...(with DryRun now working too ;-) ) 

Regards,
Eduard

**Comment by pplu** [comment]
That's because the $size you're passing to VolumeSize is undef (when it should be a number). Looks like a problem of the values you're passing. If you share your code, I can try to help you further

**Comment by Eduard3000** [comment]
Sorry, reviewing my code i forgot to replace my BDM string with the newly created var.

But just for completeness:
I parse a csv file with ec2 instances definitions, the last field contains the BDM definition:
```perl
....;[{ DeviceName => '/dev/xvda', Ebs => { DeleteOnTermination => 0,SnapshotId => 'snap-092abd885fe9dbb20', VolumeSize => 20, VolumeType => 'gp2'}},{ DeviceName => '/dev/xvdb', Ebs => { DeleteOnTermination => 0, VolumeSize => 20, VolumeType => 'gp2'}}]'
```
then I eval it into $bdm
```perl
$bdm = eval($BDMS);
```
and later use it in the RunInstances method. Volia dynamic/predefined BlockDeviceMappings 👍 :clap:

Thanks for your aid Jose!

Regards,
Eduard

**Comment by Eduard3000** [comment]
Hola, one more thing, instead of using plain eval, which could be bad if you dont sanityze the input,
use reval from the modul Safe:

```perl
use Safe;
my $comp = new Safe;
$comp->permit_only(':default');
$bdm = $comp->reval($bdms);
```
it wont execute code like sytem/eval/backticks inside $bdms :v:

Cheers,
Eduard
