### ISSUE TITLE
Cloudwatch GetMetricStatistics give perl warnings

### ISSUE THREAD

**Issue by leoncx** [pplu/aws-sdk-perl#145]
Hello,

When I use the call GetMetricStatistics form CloudWatch service without the attribute ExtendedStatistics set, I have a perl warning : 

Use of uninitialized value in anonymous hash ({}) at /usr/share/perl5/vendor_perl/Paws/Net/XMLResponse.pm line 98.

In the documentation, the ExtendedStatistics is not required.

I'm tested in version 0.31.

Example with error

```perl
use strict;
use warnings;
use Paws;

my $cw = Paws->service(
  'CloudWatch',
  'region' => 'us-east-1'
);

my $result = $cw->GetMetricStatistics(
  MetricName => 'NetworkPacketsIn',
  Namespace => 'AWS/EC2',
  Statistics => ['Average'],
  EndTime => DateTime->now->iso8601,
  StartTime => DateTime->now->subtract( minutes => 10 )->iso8601,
  Period => 600,
  Unit => 'Count',
  Dimensions => [
     { Name => 'InstanceId' , Value => 'i-xxxxxxxxx' }
  ],
);
```

Example working

```perl
use strict;
use warnings;
use Paws;

my $cw = Paws->service(
  'CloudWatch',
  'region' => 'us-east-1'
);

my $result = $cw->GetMetricStatistics(
  MetricName => 'NetworkPacketsIn',
  Namespace => 'AWS/EC2',
  Statistics => ['Average'],
  ExtendedStatistics => ['p100'],
  EndTime => DateTime->now->iso8601,
  StartTime => DateTime->now->subtract( minutes => 10 )->iso8601,
  Period => 600,
  Unit => 'Count',
  Dimensions => [
     { Name => 'InstanceId' , Value => 'i-xxxxxxxxx' }
  ],
);
```

**Comment by pplu** [comment]
Hi,

  Does the call that prints a warning work as expected?

**Comment by leoncx** [comment]
Hi,

It's work correctly, but I use this module on a program using the stdout and stderr. This warning break the parsing of the outputs.

**Comment by pplu** [comment]
I found the problem, but a bit of refactoring has to be done to get this fixed. Just for your info: the call in https://github.com/pplu/aws-sdk-perl/blob/master/lib/Paws/API/Caller.pm#L194, that was introduced to make CopyObject in S3 work causes your warning. If you are not using S3, you can consider locally patching that call.

Work on this branch: https://github.com/pplu/aws-sdk-perl/compare/feat/refactor_response_to_object is aimed at silencing the warning (among others)

**Comment by pplu** [comment]
Hi,

Version 0.32 with this bug fixed has hit the CPAN today
