### ISSUE TITLE
Elastic Transcoder Paginator Convenience Methods Not Working

### ISSUE THREAD

**Issue by SeptamusNonovant** [pplu/aws-sdk-perl#146]
Hello,

The paginator convenience methods for the Elastic Transcoder class (for example, "ListAllPresets") are not working.  The issue appears to simply be the wrong attribute name.  Instead of `$result->PageToken`, it should be `$result->NextPageToken`.

Thanks.

**Comment by pplu** [comment]
Hi!

Thanks for the report. Looks like I make a mistake in the code generation for some types of generators (a subset of services are affected by the same problem that you report).

  Can you confirm that the fix in e94fd062cc51480718bed557edd9f5a7aab5a0ec corrects the error you reported?

Thanks

**Comment by SeptamusNonovant** [comment]
Hello,

The code runs now, but it seems it just repeats the second "page" of results twice, because the Presets is being updated to the second page, then appended to itself.

I tried this for when a callback is not defined and this seems to fix things for "ListAllPresets" (not having to use a callback currently I am not sure what would need to be done for that portion):

```
  sub ListAllPresets {
    my $self = shift;

    my $callback = shift @_ if (ref($_[0]) eq 'CODE');
    my $result = $self->ListPresets(@_);
    my $next_result = $result;

    if (not defined $callback) {
      while ($next_result->NextPageToken) {
        $next_result = $self->ListPresets(@_, PageToken => $next_result->NextPageToken);
        push @{ $result->Presets }, @{ $next_result->Presets };
      }
      return $result;
    } else {
      while ($result->NextPageToken) {
        $result = $self->ListPresets(@_, PageToken => $result->NextPageToken);
        $callback->($_ => 'Presets') foreach (@{ $result->Presets });
      }
    }

    return undef
  }
```

Hope this helps.

Thanks.

**Comment by pplu** [comment]
Just pushed 0.33 to CPAN with this issue solved
