### ISSUE TITLE
Paws::DynamoDB::PutItem returning error

### ISSUE THREAD

**Issue by jglesner** [pplu/aws-sdk-perl#153]
Receiving the following hash ref error message: 
**Can't use string ("TEST") as a HASH ref while "strict refs" in use at Paws/API/Caller.pm line 27, <DATA> line 1.**

... with the code, to put an item into a dynamo db table named KeyCatalog: 
```
use Paws;
my $dynamo = Paws->service('DynamoDB', region => 'us-east-1');
my $tableName = "KeyCatalog";
my $key = 'TEST';
$dynamo->PutItem(Item => { keyName => $key },TableName => $tableName);
```

In this example, keyName is the partition key, and its configured to be a string. Am I doing something wrong, or is there a bug? 

Thanks!

**Comment by pplu** [comment]
Hi,

It looks like it's `keyName => { 'S' => $key }`. Take a look at examples/dynamodb.pl to get a grip of how to structure the call to dynamodb (it doesn't accept arbitrary hashes).

Some time ago (Issue #77) @bluefeet worked on a library for converting arbitrary hashes to a dynamodb structure. I haven't seen it on CPAN. Maybe he can upload it (if he feels it's ready).

**Comment by pplu** [comment]
Hi,
  Was your problem solved?

**Comment by pplu** [comment]
Hi,

 I'm closing this bug report
