### ISSUE TITLE
Performance improvements in credential refreshing

### ISSUE THREAD

**Issue by frioux** [pplu/aws-sdk-perl#158]
I found that this line of code shows up pretty quickly in profiles:

```perl
return if (($self->expiration - DateTime->now())->is_positive);
```

I can trivially refactor it to:

```perl
return if $self->expiration >= time;
```

if we assume expiration is seconds since epoch, instead of a full on DateTime object.

I will submit a patch as soon as you can tell me if you want to retain the DateTime interface or if it's ok to change since it's undocumented.

Let me know.

**Comment by pplu** [comment]
I think it's OK to abandon the DateTime interface (it was initially public so it could be easily tested, which continues to be the case). Thanks for work :+1:
