### ISSUE TITLE
Posibility to obtain Credentials from ~/.aws/credentials file

### ISSUE THREAD

**Issue by ghost** [pplu/aws-sdk-perl#16]
It would be great to have the option to get the API credentials from an ~/.aws/credentials file. 

Above you can see an example of the format of that file:
[default]
aws_access_key_id = YOUR_AWS_ACCESS_KEY_ID
aws_secret_access_key = YOUR_AWS_SECRET_ACCESS_KEY

More details about the format are explained in that URL:
 * http://docs.aws.amazon.com/aws-sdk-php/guide/latest/credentials.html

**Comment by pplu** [comment]
Hi!

Done in commit 95248da016272be5ffecc72b2af7646872323e89. Please remember to read the Changes file before pulling the new version :)

**Comment by pplu** [comment]
After implementing your suggestion, I thought that the namespaces for the credential providers weren't good. I've been changing them, so be aware, although the basic external API hasn't changed
