### ISSUE TITLE
outdated/broken plugin in dist.ini

### ISSUE THREAD

**Issue by karenetheridge** [pplu/aws-sdk-perl#162]
Dist::Zilla::Plugin::VersionFromModule no longer works with the latest Dist::Zilla, and there is no indication the author will come back anytime soon to do a release; I recommend changing either to Dist::Zilla::Plugin::VersionFromMainModule (a drop-in replacement) or Dist::Zilla::Plugin::RewriteVersion and Dist::Zilla::Plugin::BumpVersionAfterRelease (what I use; a bit smarter as you no longer have to increment versions manually anymore).

**Comment by pplu** [comment]
Thanks!

  I had no idea that module was going to break. Thanks for the pre-warning!

  I would love to know a bit more about Dist::Zilla, but it's been very hard for me to find good documentation. If you could propose a setup that you think adequate for Paws (or that you like best), then maybe I can learn by example from the pros :bowing_man:

   There are some things I have on my TODO that I think are Dist::Zilla accomplishable:
   - I would like to not be able to dzil build with things pending for commit
   - Sometimes I forget to tag the version that was released
   - Auto upload to PAUSE after release (I tried to configure this, but never got it to work)
   - I would love to distribute Paws in one dist per AWS service (so you don't have to install a bazillion services just to use one) (you already said it was complicated, but I have no idea where to start)

BTW: I've applied your change in the branch prepare_for_032

**Comment by karenetheridge** [comment]
- to not build with changes you haven't committed yet, you would have to stash your edits (see `git stash`). You can prevent a release from happening if you have uncommitted changes with the `[Git::Check]` plugin:

    [Git::Check / initial check]
    allow_dirty =

- PAUSE uploads can be done with the `[UploadToCPAN]` plugin -- you need to have your userid/password recorded somewhere - I just use a plain-text ~/.pause file, but you can also GPG-encrypt it using Config::Identity (I wasn't able to get this to work when I tried a few years back, and haven't bothered trying again)

- `[Git::Tag]` is good for tagging a release (and then `[Git::Push]` will push the changes to github automatically... The configuration I use is recorded here -- https://metacpan.org/pod/Dist::Zilla::PluginBundle::Author::ETHER#DESCRIPTION -- I use default config options for a lot of things; the main trick is getting the plugin ordering correct.


- from a user perspective, multiple distributions would be lovely!  the Paws code currently comprises about half of our ~14000 installed modules :)   Can you create a new issue ticket describing how you want to break up the code into distributions? I might be able to find some time over the next few months to propose something. (I release all the Task-Kensho-* distributions from one repository using a few small scripts to automate the process.. the work is mostly in creating the `dist.ini` configuration files for each distribution.)

**Comment by Grinnz** [comment]
~/.pause is not needed to use [UploadToCPAN]. It will prompt for pause ID and password if not found.

I recommend also using [ConfirmRelease] just before [UploadToCPAN] as most bundles do, which will prompt if you are really ready to release (after running release tests).

You don't have to use it, but I tried to document several of the basics in the documentation for https://metacpan.org/pod/Dist::Zilla::PluginBundle::Starter; maybe it will be helpful too.

**Comment by pplu** [comment]
Thanks to the two of you: I'll try out your suggestions for the release I'm preparing today

@karenetheridge I've updated Issue #48 with some thoughts on how the dist can be splitted
