### ISSUE TITLE
S3 GetBucketPolicy fails

### ISSUE THREAD

**Issue by sven-schubert** [pplu/aws-sdk-perl#168]
I currently have an issue with the S3 module of Paws (version 0.32). I'm trying to execute the GetBucketPolicy call fails. My guess is that the module expects a xml response, but gets a simple json-string.

$paws->GetBucketPolicy(Bucket => 'backupmaster-irl');
Error message is:
File does not exist: {"Version":"2012-10-17","Statement":[{[...]]}}}]} at /opt/gmp-perl/perls/perl-5.24.0/lib/site_perl/5.24.0/Paws/Net/RestXMLResponse.pm line 13.
 at /opt/gmp-perl/perls/perl-5.24.0/lib/site_perl/5.24.0/XML/Simple.pm line 964.
XML::Simple::find_xml_file(XML::Simple=HASH(0x80099f8), "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"DenyUnEncryptedO"...) called at /opt/gmp-perl/perls/perl-5.24.0/lib/site_perl/5.24.0/XML/Simple.pm line 239
XML::Simple::parse_file(XML::Simple=HASH(0x80099f8), "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"DenyUnEncryptedO"..., "ForceArray", ARRAY(0x7f6c378), "KeyAttr", "", "SuppressEmpty", undef) called at /opt/gmp-perl/perls/perl-5.24.0/lib/site_perl/5.24.0/XML/Simple.pm line 219
XML::Simple::XMLin("{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"DenyUnEncryptedO"..., "ForceArray", ARRAY(0x7f6c378), "KeyAttr", "", "SuppressEmpty", undef) called at /opt/gmp-perl/perls/perl-5.24.0/lib/site_perl/5.24.0/Paws/Net/RestXMLResponse.pm line 13
Paws::Net::RestXMLResponse::unserialize_response(Paws::S3=HASH(0x79cdb08), "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"DenyUnEncryptedO"...) called at /opt/gmp-perl/perls/perl-5.24.0/lib/site_perl/5.24.0/Paws/Net/RestXMLResponse.pm line 32
Paws::Net::RestXMLResponse::handle_response(Paws::S3=HASH(0x79cdb08), Paws::S3::GetBucketPolicy=HASH(0x76ad728), 200, "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"DenyUnEncryptedO"..., HASH(0x7f570e0)) called at /opt/gmp-perl/perls/perl-5.24.0/lib/site_perl/5.24.0/Paws/Net/Caller.pm line 40
Paws::Net::Caller::caller_to_response(Paws::Net::Caller=HASH(0x6a75fc0), Paws::S3=HASH(0x79cdb08), Paws::S3::GetBucketPolicy=HASH(0x76ad728), 200, "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"DenyUnEncryptedO"..., HASH(0x7f570e0)) called at /opt/gmp-perl/perls/perl-5.24.0/lib/site_perl/5.24.0/Paws/Net/RetryCallerRole.pm line 19
Paws::Net::RetryCallerRole::do_call(Paws::Net::Caller=HASH(0x6a75fc0), Paws::S3=HASH(0x79cdb08), Paws::S3::GetBucketPolicy=HASH(0x76ad728)) called at /opt/gmp-perl/perls/perl-5.24.0/lib/site_perl/5.24.0/Paws/S3.pm line 245
Paws::S3::GetBucketPolicy(Paws::S3=HASH(0x79cdb08), "Bucket", "backupmaster-irl")

**Comment by sven-schubert** [comment]
solution: https://github.com/pplu/aws-sdk-perl/pull/187

**Comment by sven-schubert** [comment]
proper solution for generating files: https://github.com/pplu/aws-sdk-perl/pull/196

**Comment by pplu** [comment]
This was shipped on 0.35
