### ISSUE TITLE
S3::PutBucketPolicy fails

### ISSUE THREAD

**Issue by sven-schubert** [pplu/aws-sdk-perl#169]
Can't locate object method "meta" via package "{"Version":"2012-10-17","Statement":[{"Resource":"arn:aws:s3:::hec-log-irl/*","Effect":"Deny",...]}" perhaps you forgot to load "{"Version":"2012-10-17","Statement":[{"Resource":"arn:aws:s3:::hec-log-irl/*","Effect":"Deny",...]}"?) at /opt/gmp-perl/perls/perl-5.24.0/lib/site_perl/5.24.0/Paws/Net/RestXmlCaller.pm line 121.

pull-request to solve the issue: https://github.com/pplu/aws-sdk-perl/pull/170

**Comment by pplu** [comment]
Just pushed 0.33 to CPAN with this issue solved

**Comment by sven-schubert** [comment]
Thank you.
