### ISSUE TITLE
PAWS ACM ImportCertificate returns spurious error

### ISSUE THREAD

**Issue by jaybonci** [pplu/aws-sdk-perl#173]
Thank you for all the work on this module. I've run into an error with ACM ImportCertificate. I understand that the error message is being passed back from AWS, but when I upload it through the interface, it's going in just fine, which makes me think it's some kind of formatting error on the arguments

Any ideas? I'm happy to help debug.

``The private key is not supported. Only RSA 1024-bit and 2048-bit private keys are allowed.

Trace begun at /var/paws/lib/Paws/Net/JsonResponse.pm line 32
Paws::Net::JsonResponse::handle_response('Paws::ACM=HASH(0x60f0650)', 'Paws::ACM::ImportCertificate=HASH(0x5d64458)', 400, '{"__type":"ValidationException","message":"The private key is not supported. Only RSA 1024-bit and 2048-bit private keys are allowed."}', 'HASH(0x643e708)') called at /var/paws/lib/Paws/Net/Caller.pm line 40
Paws::Net::Caller::caller_to_response('Paws::Net::Caller=HASH(0x5f61888)', 'Paws::ACM=HASH(0x60f0650)', 'Paws::ACM::ImportCertificate=HASH(0x5d64458)', 400, '{"__type":"ValidationException","message":"The private key is not supported. Only RSA 1024-bit and 2048-bit private keys are allowed."}', 'HASH(0x643e708)') called at /var/paws/lib/Paws/Net/RetryCallerRole.pm line 19
Paws::Net::RetryCallerRole::do_call('Paws::Net::Caller=HASH(0x5f61888)', 'Paws::ACM=HASH(0x60f0650)', 'Paws::ACM::ImportCertificate=HASH(0x5d64458)') called at /var/paws/auto-lib/Paws/ACM.pm line 40``

**Comment by pplu** [comment]
Hi,

  Maybe your problem is that you are not base64 encoding the values to ImportCertificate (Paws does not do this automatically (yet))

 See http://docs.aws.amazon.com/acm/latest/APIReference/API_ImportCertificate.html for more info.

Hope it helps!

**Comment by jaybonci** [comment]
That was absolutely the problem. I had assumed the PEM format, since it is base64 in the middle was sufficient, but it's clear they mean the entire blob. 
I hope someone else finds this and it helps them as well. Thank you so much for your prompt support.
