### ISSUE TITLE
Future::Mojo not listed as a dependency

### ISSUE THREAD

**Issue by karenetheridge** [pplu/aws-sdk-perl#175]
Future::Mojo seems to be used by Paws::Net::MojoAsyncCaller, so it should be added as a runtime dependency.

**Comment by Grinnz** [comment]
It's only needed if you actually want to use MojoAsyncCaller, so it's considered an optional dependency as I understand it.

**Comment by karenetheridge** [comment]
ah, ok -- perhaps that should be a runtime-suggests prereq then, or possibly in META as an optional_feature (the `[OptionalFeature]` dzil plugin can add this). presently it's only listed as a develop prereq.

**Comment by pplu** [comment]
Would that work correctly by adding `suggests "Future::Mojo";` to the cpanfile?

**Comment by Grinnz** [comment]
Yes, that would add a runtime suggests, so it would at least show up in metadata.

**Comment by pplu** [comment]
Already in branch release/0.33, ready for next release

**Comment by pplu** [comment]
Just pushed 0.33 to CPAN with this issue solved
