### ISSUE TITLE
Input on naming of related module

### ISSUE THREAD

**Issue by stevecaldwell77** [pplu/aws-sdk-perl#178]
@pplu - I'm developing a module to make it simpler to do common DynamoDB tasks using Paws:

  https://github.com/stevecaldwell77/PawsX-DynamoDB-DocumentClient

(it's based on the [DocumentClient class](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html) in the AWS JavaScript SDK).

I wanted to get your input on naming before I publish it to CPAN (it'll probably be ready by tomorrow). I was concerned that naming it Paws::DynamoDB::DocumentClient would hijack Paws's namespace and theoretically cause issues in the future, so I used 'PawsX' instead. But now I'm having misgivings about introducing an entirely new top-level namespace just for my module.

Thoughts?

**Comment by pplu** [comment]
Hey! Neat! This looks great!

Also: I like the namespace election you made: Paws::Service classes all share a certain form so the class loader can pass a set of common attributes to them, so I wouldn't put stuff in the Paws namespace. PawsX super-good to me :+1: 

Also, with this module you'll be solving #41 and #77. I'm open to linking to your module to help people find it easily

**Comment by stevecaldwell77** [comment]
> Also: I like the namespace election you made

I like an answer that makes it so I don't have to change anything :) Thanks.

> I'm open to linking to your module to help people find it easily

Much appreciated. I'll keep you posted.

**Comment by stevecaldwell77** [comment]
@pplu - OK. it's published:

  https://metacpan.org/pod/PawsX::DynamoDB::DocumentClient
