### ISSUE TITLE
Paws 0.35 is not indexed

### ISSUE THREAD

**Issue by karenetheridge** [pplu/aws-sdk-perl#200]
It's not clear to me what the problem is, but the email you got from PAUSE after uploading the distribution may provide a clue -- the 0.35 release doesn't seem to have been indexed by PAUSE and the cpan mirrors.

**Comment by pplu** [comment]
It usually takes some hours...

**Comment by Grinnz** [comment]
It may take an hour or so for metacpan to show it as indexed, but in this case, it hasn't been indexed in PAUSE at all. The email you received when uploading would have the explanation. http://cpanmeta.grinnz.com/packages#=Paws

**Comment by pplu** [comment]
@karenetheridge: The upload was done at 9-Oct 21:20 PM. I received the upload email from PAUSE immediately. The "PAUSE indexer report" email at 2:46 AM (10-Oct). I think that more or less all Paws uploads have taken that much time to get indexed.

**Comment by karenetheridge** [comment]
Thanks. 0.35 appears in the index now.  This is a very unusual delay however -- PAUSE rarely takes more than an hour to index any distribution that I've uploaded.

**Comment by pplu** [comment]
> This is a very unusual delay however -- PAUSE rarely takes more than an hour to index any distribution that I've uploaded
My guess is that the delay is because of the number of files in the dist. My other dists behave as you state when uploaded.
