### ISSUE TITLE
[BUG] Batch->SubmitJob Doesn't pass JobName properly.

### ISSUE THREAD

**Issue by pprocacci** [pplu/aws-sdk-perl#201]
I have the following perl snippet executing which is failing:

==============
        my $lwp_caller = new Paws::Net::LWPCaller( debug => 1 );
        my $batch = Paws->service('Batch', caller => $lwp_caller, region => $region);

        my $res = $batch->SubmitJob(
                JobDefinition => $ENV{JOB_DEFINITION},
                JobName => 'testing',
                JobQueue => $ENV{JOB_QUEUE},
                ContainerOverrides => {
                        Environment => [
                                { Name => 'ENGINE', Value => $engine },
                                { Name => 'PORT', Value => $port },
                                { Name => 'IDENTIFIER', Value => $identifier },
                                { Name => 'ENDPOINT', Value => $endpoint },
                                { Name => 'DATABASE', Value => $database },
                                { Name => 'TABLE', Value => $table },
                        ]
                }
        );
================

This always fails with "Error executing request, Exception : Job name must be provided".
Clearly job name is defined as I'm hard coding it for testing.

Please help rectify this problem.
Thanks

**Comment by pplu** [comment]
Hi,
   I see what's wrong here: the SDK is not sending the fields correctly back to the server. In http://docs.aws.amazon.com/batch/latest/APIReference/API_SubmitJob.html, JobQueue should be jobQueue. Let me see if I can get you a quick fix up there...

**Comment by pplu** [comment]
Hello,

Can you try with the code in this branch? https://github.com/pplu/aws-sdk-perl/tree/fix/restjson-requestnames

**Comment by pplu** [comment]
Hi,

  Did it work?

**Comment by pprocacci** [comment]
Don't know yet.  I'm not at all familiar with git, so I'm trying to figure it out.  Sorry.

**Comment by pplu** [comment]
Ok, let me try to get you running:

We want to get the code for the branch I prepared for you to test
```
git clone https://github.com/pplu/aws-sdk-perl.git
# will create a directory called aws-sdk-git
cd aws-sdk-git
git checkout fix/restjson-requestnames
pwd
```
pwd will output the path to your checked out code.

Now in your Perl project, you can try to load Paws, overriding whats installed on your system:
```
perl -I /path/to/paws_clone/lib -I /path/to/paws_clone/auto-lib your_program
```
Hope it helps 😃

**Comment by pprocacci** [comment]
I actually created my own diff based on your changes.  The diffs I stole work:

##########################################################################

/usr/local/share/perl5/site_perl/Paws/Batch # diff -u SubmitJob.pm.orig SubmitJob.pm
--- SubmitJob.pm.orig
+++ SubmitJob.pm
@@ -1,13 +1,13 @@
 
 package Paws::Batch::SubmitJob;
   use Moose;
-  has ContainerOverrides => (is => 'ro', isa => 'Paws::Batch::ContainerOverrides');
-  has DependsOn => (is => 'ro', isa => 'ArrayRef[Paws::Batch::JobDependency]');
-  has JobDefinition => (is => 'ro', isa => 'Str', required => 1);
-  has JobName => (is => 'ro', isa => 'Str', required => 1);
-  has JobQueue => (is => 'ro', isa => 'Str', required => 1);
-  has Parameters => (is => 'ro', isa => 'Paws::Batch::ParametersMap');
-  has RetryStrategy => (is => 'ro', isa => 'Paws::Batch::RetryStrategy');
+  has ContainerOverrides => (is => 'ro', isa => 'Paws::Batch::ContainerOverrides',traits => ['NameInRequest'], request_name => 'containerOverrides');
+  has DependsOn => (is => 'ro', isa => 'ArrayRef[Paws::Batch::JobDependency]',traits => ['NameInRequest'], request_name => 'dependsOn');
+  has JobDefinition => (is => 'ro', isa => 'Str', required => 1,traits => ['NameInRequest'], request_name => 'jobDefinition',);
+  has JobName => (is => 'ro', isa => 'Str', required => 1, traits => ['NameInRequest'], request_name => 'jobName');
+  has JobQueue => (is => 'ro', isa => 'Str', required => 1, traits => ['NameInRequest'], request_name => 'jobQueue');
+  has Parameters => (is => 'ro', isa => 'Paws::Batch::ParametersMap',traits => ['NameInRequest'], request_name => 'parameters');
+  has RetryStrategy => (is => 'ro', isa => 'Paws::Batch::RetryStrategy', traits => ['NameInRequest'], request_name => 'retryStrategy');
 
   use MooseX::ClassAttribute;

**Comment by pprocacci** [comment]
And I guess, copying/pasting through this interface stinks......
In either case, the changes are working...

**Comment by pplu** [comment]
🎈 🎉  happy it works! (please take care when calling more things in Batch to apply the rest of the changes)

**Comment by pplu** [comment]
Just pushed 0.36 to CPAN with this issue fixed
