### ISSUE TITLE
incorrect files included

### ISSUE THREAD

**Issue by chorny** [pplu/aws-sdk-perl#21]
Your distribution contains file Makefile. This file should not be included into distribution - it is generated when installing.

**Comment by pplu** [comment]
OK, but where should I move the things that are in the Makefile? Is there any alternate place to put them? (it's very convenient to type make COMMAND, and it even has autocompletion so I don't have to remember if it's "pull-other-sdks" or "pullothersdks", for example :)

Do you think that putting the Makefile in the exclude_match of the [Git::GatherDir] in dist.ini would be good? (I think that way we can leave it in git, but not distribute it in CPAN dists)

**Comment by chorny** [comment]
> Do you think that putting the Makefile in the exclude_match of the [Git::GatherDir] in dist.ini would be good?

Should be enough.

**Comment by pplu** [comment]
d56cbd7b02780f7eeb73b0422ac6a15ec1205a6c has the file excluded :)
