### ISSUE TITLE
PutObject failing for 0.35

### ISSUE THREAD

**Issue by glenveegee** [pplu/aws-sdk-perl#210]
Looks like the PutObject request is being corrupted between submitting on the client and reception at Amazons end with a dodgy MD5 digest of the contents.

PutObject requests fail with the following error
```xml
<Error>
  <Code>BadDigest</Code>
  <Message>The Content-MD5 you specified did not match what we received.</Message>
  <ExpectedDigest>d41d8cd98f00b204e9800998ecf8427e</ExpectedDigest>
  <CalculatedDigest>AhKbuGEGHRoFLFkuLcazgw==</CalculatedDigest>
  <RequestId>XXXXXXXXXXXXX</RequestId>
  <HostId>xxxxxxxxxxxxxx</HostId>
</Error>
```

It turns out that the "ExpectedDigest" is always d41d8cd98f00b204e9800998ecf8427e which just so happens to be the md5 checksum of an empty string

```
> md5 -qs ''
d41d8cd98f00b204e9800998ecf8427e
```

So it would appear that the Body is not being set correctly under some circumstances.

I don't believe I'm doing anything complicated. My request is as follows:

```perl
$s3->PutObject(
      Bucket          => $bucketname,
      Key             => $remote_file_path,
      Body            => q[This is a test],
    );
```

**Comment by pprocacci** [comment]
http://docs.aws.amazon.com/cli/latest/reference/s3api/put-object.html

If putObject follows the convention used in the aws documentation, the body parameter takes an object from the file system for use within the function call.  To put it another way, 'object data' isn't a memory buffer, but rather a file on disk that gets read.  You can see this within their 'Examples' section.

$s3->PutObject(
      Bucket          => $bucketname,
      Key             => $remote_file_path,
      Body            => '/path/to/file',
    );

**Comment by lukec** [comment]
I'm seeing this in 0.35 as well.  On versions prior to 0.35 I could upload using:

`$s3->PutObject(Body => $content, Key => $path, Bucket => $bucketname)`

And it would take the content (in my case binary image data) and put it in S3.  Now with the 0.35 it tries to add the Content MD5 header, but calculates it incorrectly and so the server rejects the request.

**Comment by glenveegee** [comment]
Hi pprocacci,

You are absolutely correct in saying that the awscli (s3api) command line
tool uses file path. Internally this tool must still be reading in the file
as bytes and submitting it in a request body to AWS API.  Paws follows the
API design as described in the botocore definitions and as such should
accept either string or bytes for the Body argument. See
http://boto3.readthedocs.io/en/latest/reference/services/s3.html#S3.Object.put

Python boto3 and Paws are 'in principle' built from the same API definition
files as far as I understand and you will notice in the put request that
only string or bytes are accepted for the Body argument.

// G

**Comment by glenveegee** [comment]
See https://github.com/pplu/aws-sdk-perl/pull/211 for a temporary workaround

**Comment by pplu** [comment]
Just pushed 0.36 to CPAN with this issue fixed
