### ISSUE TITLE
META.yml

### ISSUE THREAD

**Issue by chorny** [pplu/aws-sdk-perl#22]
This distribution lacks META.yml file. This file contains information that allows CPAN tools to be more effective (ex: http://search.cpan.org, http://deps.cpantesters.org/).

**Comment by pplu** [comment]
Do you know if there's a way to generate it via Dist::Zilla?

**Comment by chorny** [comment]
AFAIK,
```
dzil build
```
should generate it automatically.

**Comment by pplu** [comment]
That's how I building the package. Taking a look, I've found the way to generate it in 2941c0067627ecf49c78197ff969d09a0548352a

Thanks for the feedback!
