### ISSUE TITLE
Use the examples-1.json in botocore to create better example code

### ISSUE THREAD

**Issue by castaway** [pplu/aws-sdk-perl#227]
I'm being sponsored by ZipRecruiter to have a go at improving some of the Paws generated documentation. This is one of the items on my list.

The botocore source code contains, for about half of the services, an examples-1.json file containining examples for the API methods. I'd like to translate these examples into synopses for the appropriate call class documentation where they exist.

It looks like this could be achieved by adding attributes to Paws::API::Builder  for the examples.json filename and its contents, and constructing the examples in the callclass template.

**Comment by pplu** [comment]
Paws 0.37 with this change has just been uploaded to CPAN
