### ISSUE TITLE
bad handling of firehose serialization exceptions?

### ISSUE THREAD

**Issue by karenetheridge** [pplu/aws-sdk-perl#237]
In the last few days, the firehose service has been spewing a lot of
"SerializationException" errors apparently at random (which is out of the
scope of this ticket as that's beyond your control). However, the exception
handler has not been parsing the response properly. turning it into
"Unrecognized error format".

Here is the response I am getting from the network (as dumped from
Paws::Net::Caller::send_request):

    {
      'success' => '',
      'protocol' => 'HTTP/1.1',
      'headers' => {
                     'x-amzn-requestid' => ...,
                     'connection' => 'close',
                     'content-type' => 'application/x-amz-json-1.1',
                     'date' => ...,
                     'x-amz-id-2' => ...,
                     'content-length' => ...,
                   },
      'status' => '400',
      'url' => 'https://firehose.us-east-1.amazonaws.com/',
      'content' => '{"__type":"SerializationException"}',
      'reason' => 'Bad Request'
    };

And this is transformed into the exception object:

       bless( {
         'stack_trace' => ...,
         'http_status' => 400,
         'previous_exception' => undef,
         'message' => 'Unrecognized error format',
         'stack_trace_class' => 'Devel::StackTrace',
         'stack_trace_args' => ...,
         'request_id' => ...,
         'code' => 'SerializationException'
       }, 'Paws::Exception' );

It looks like maybe Paws::Net::JsonResponse::error_to_exception could be
handling this better?

**Comment by pplu** [comment]
Hi,

   Thanks for the feedback. I'd like to know what part of the conversion to the exception object you think could be handled better. Is it maybe the `unrecognized error format` message?

   On the other hand, do you think that these SerializationExceptions could be due to something that Paws is (or isn't) doing that could be handled by Paws? Can you give me a couple of examples of what parameters are being passed to what methods that end up rising those errors? (On the other side, maybe you can ask AWS support the why of this apparent randomness (the request_id in the exception should help them out).

**Comment by karenetheridge** [comment]
Yes, "unrecognized error format" suggests that maybe they're now sending errors in a new format that should be parsed better.  It would be nice if the error message in the http response was more specific (what was wrong with the serialization? we have no idea), but Paws can't do anything about that as no more information is included.

This script is enough to reproduce the errors, sporadically...

    use strict;
    use warnings;
    use MIME::Base64 'encode_base64';
    use JSON::MaybeXS;
    use Try::Tiny;
    use Scalar::Util 'blessed';
    use Paws;

    # the actual data being sent doesn't seem to matter...
    my $data = {
        'a' => 1,
        'b' => 2,
        'c' => 3,
    };

    my $stream_name = '...';        # your stream here
    log_to_firehose($stream_name, $data);
    log_to_firehose($stream_name, $data);


    sub log_to_firehose {
        my ($stream_name, $data) = @_;

        my $service = Paws->service('Firehose',
            region      => 'us-east-1',
            credentials => ...,                 # your credentials here
        );

        try {
            $service->PutRecord(
                DeliveryStreamName => $stream_name,
                Record => {
                    Data => encode_base64(encode_json($data) . "\n"),
                },
            );
        } catch {
            my $error = $_;
            if (blessed($error) and $error->isa('Paws::Exception')) {
                $error = encode_json({
                    code        => $error->code,
                    request_id  => $error->request_id,
                    http_status => $error->http_status,
                    message     => $error->message,
                    # stack_trace => $error->stack_trace->as_string,
                });
            }
            # log error here...
            print STDERR "### got error: $error\n";
        };
    }

**Comment by pplu** [comment]
@Grinnz You'll never go to bed without learning something new... I hadn't realized that encode_base64 feature although it's clearly documented :fearful:

**Comment by karenetheridge** [comment]
> Do you think that putting the exceptions code in the message if there is no message (that would be message => 'SerializationException' for this case) works better?

Yes, that sounds like a good way of handling it.

We've got someone pursuing the issue with Amazon to see what's wrong with our data.. hopefully it will be something obvious and stupid that I can easily fix :)

**Comment by pplu** [comment]
Just pushed the exception handling changes. Can you test if everything is OK?

> We've got someone pursuing the issue with Amazon to see what's wrong with our data.. hopefully it will be something obvious and stupid that I can easily fix :)

Please do tell us the cause, even if you guys think it's stupid: we all do stupid things at times (it's very probable it ends up helping someone).

**Comment by pplu** [comment]
Paws 0.37 with this change has just been uploaded to CPAN

BTW: did you find out what was wrong with your data?

**Comment by karenetheridge** [comment]
We did not ever hear about what the issue was with our data. :(

Thank you very much for the change; we are not experiencing problems at the moment so it is difficult to see how different the exception looks, but the commits you applied look quite sensible. Thanks again!
