### ISSUE TITLE
0.37 - docu_links throws "missing documentation-1.json" errors

### ISSUE THREAD

**Issue by castaway** [pplu/aws-sdk-perl#249]
make docu-links -> documentation-1.json missing for the service, run 'make docu-links'. at builder\
-lib/Paws/API/Builder.pm line 206

**Comment by piratefinn** [comment]
Figured the issue, requires moving the file check to documentation_struct as documentation_file is used to get the string regardless if the file exists or not (due to being used both with the doc file writer and later in documentation_struct). Will make a PR in a moment

**Comment by pplu** [comment]
Merged #250.
BTW: due to release of 0.37 to CPAN, I've started the release/0.38 branch for active development
