### ISSUE TITLE
Namespace collision for Paws::SQS::AttributeMap

### ISSUE THREAD

**Issue by codehead** [pplu/aws-sdk-perl#25]
Both Paws::SQS::Message->Attributes and Paws::SQS::GetQueueAttributesResult->Attributes return a Paws::SQS::AttributeMap object. The first object should contain *message* attributes (e.g. SentTimestamp) and the second *queue* attributes (e.g. MessageRetentionPeriod).
Just to add to the confusion, there's a Paws::SQS::MessageAttributeMap object for user-defined metadata, which works fine but is totally unrelated to either of these.
I wonder what would be the best way to fix this without breaking the automagical object generation mojo.

**Comment by pplu** [comment]
I'm taking a look at it. Have to confirm if the definition files specify the same name, or if the autogeneration is just choosing the wrong names for the shapes :)

**Comment by pplu** [comment]
Can you tryout / verify if https://github.com/pplu/aws-sdk-perl/commit/ae3408485fd16c8455c22cc2372d53e5d71bf5c2 is correct? It looks like the botocore sqs definitions (checking out the master should give you that changeset)

**Comment by codehead** [comment]
Great, it certainly fixes the Queue side of the deal! I just did a PR to fix Paws::SQS::AttributeMap
Thanks for the prompt action!

**Comment by pplu** [comment]
Paws 0.09 (released to CPAN today) has your changes applied :)
