### ISSUE TITLE
Paws::DynamoDB::AttributeValue doesn't have an access_token at /Users/user/pkg/lib/perl5/site_perl/5.26.0/Paws/DynamoDB.pm line 166.

### ISSUE THREAD

**Issue by donomii** [pplu/aws-sdk-perl#286]
While attempting 

```perl
     while (my $last =  $QueryOutput->{LastEvaluatedKey}) { 
     $QueryOutput = $dynamodb->Scan('TableName' => $table, ExclusiveStartKey=>$last);
 }
```

The initial query works, the next scan doesn't.

**Comment by pplu** [comment]
Hi,
   Can you give me more context, or a working example of how to reproduce the error? It would seem that the error comes from coercing the response into an object. Can you dump the HTTP response in `lib/Paws/Net/Caller.pm`, just about here https://github.com/pplu/aws-sdk-perl/blob/master/lib/Paws/Net/Caller.pm#L33

**Comment by donomii** [comment]
I apologise, there is too much sensitive data in the table for me to copy.  However I can answer questions and post snippets.  e.g., the http response contains:

```json
"LastEvaluatedKey":{"access_token":{"S":"redacted 406 character string"}}
```

**Comment by pplu** [comment]
OK. Please provide the stack trace of the call that fails. Redact any sensitive information that you feel.

One strange thing is; You are accessing `$QueryOutput->{LastEvaluatedKey}` as a hash. If this is a Paws object it should be accessed as a method `$QueryOutput->LastEvaluatedKey`. This shouldn't be the cause of your problem, but I don't have enough context yet :)

**Comment by pplu** [comment]
I ***think*** I know what's wrong: LastEvaluatedKey is a Map object. Scan expects a HashRef in the ExclusiveStartKey I think the problem is that you have to pass a hashref of the form `{ access_token => { S => 'value } }` to LastEvaluatedKey, while probably what is in $last isn't a HashRef like that.

**Comment by donomii** [comment]
That was it!

Thank you very much for helping me.  The output from ```$QueryOutput->LastEvaluatedKey``` can not be used as a valid ```ExclusiveStartKey=>``.  ie this can not work:

```perl
    $dynamodb->Scan('TableName' => $table, ExclusiveStartKey=>$QueryOutput-LastEvaluatedKey);
```

I guess I would make this a feature request, since the documentation implies (but does not state!) that I should use the output from LastEvaluatedKey as an ExclusiveStartKey.  Or maybe update the documentation to let people know that they have to call ```$QueryOutput->LastEvaluatedKey->Map``` to get the key for the next scan.

Although I guess if it has been like this for so long, everybody must be using the batch interface and not the scan interface...

Thanks again!
