### ISSUE TITLE
Document the retry logic

### ISSUE THREAD

**Issue by leonerd** [pplu/aws-sdk-perl#296]
From reading the code, it seems that the callers all implement some retry logic around failures (#295 notwithstanding). However, this ability doesn't appear to be mentioned in documentation - there's no discussion of what and how it works, nor pointing out how users can adjust things like retry counts and timeouts.

As the docs are all automatically generated, I suspect fixing this will involve some adjustment to the template files in the `templates/` directory.

(This is largely a placeholder issue as I'm mostly intending to fix it myself, but I would like some guidance on exactly what and where to write about things)

**Comment by Grinnz** [comment]
The docs aren't *all* automatically generated, just the docs for the individual services and Paws.pm itself. That said this might have to go in Paws.pm, since Paws::Net::CallerRole and Paws::Net::*Caller don't have any docs of their own currently. Paws.pm docs appear to be in https://github.com/pplu/aws-sdk-perl/blob/master/builder-lib/Paws/API/Builder/Paws.pm .

**Comment by leonerd** [comment]
I was thinking there'd be two parts to this:
  1) an overall description of what retry logic looks like and how users can override it - that could go in Paws.pm itself or wherever.
  2) a brief per-service explaination of what the defaults are - retries, timeouts, etc...

**Comment by leonerd** [comment]
Unable to rebuild docs currently due to #303

**Comment by pplu** [comment]
Hi @leonerd : As of now a clean checkout isn't generating exactly the same code. Please work on this parting from the release/0.39 branch. The Paws.pm file is generated from `templates/default/paws_pm.tt`. Don't worry about the changed service files, I'll handle them on merge.

**Comment by pplu** [comment]
Released to CPAN with Paws 0.39
