### ISSUE TITLE
AutoScaling: Mixed Instances Policy support

### ISSUE THREAD

**Issue by Prajithp** [pplu/aws-sdk-perl#304]
Could you please update the botocore definition to add support for MixedInstancesPolicy?

**Comment by pplu** [comment]
Hi,
   Look in release/0.39 branch. It should be there. Please tell me if it works for you.

**Comment by Prajithp** [comment]
Thanks @pplu will test it out and update you.

**Comment by Prajithp** [comment]
This is failing in release/0.39 branch with following error.

Valid requests must contain either LaunchTemplate, LaunchConfigurationName or MixedInstancesPolicy parameter.

Trace begun at /opt/deployer/embedded/lib/perl5/site_perl/5.24.4/Paws/Net/XMLResponse.pm line 46
Paws::Net::XMLResponse::process('Paws::Net::XMLResponse=HASH(0x5e906d8)', 'Paws::AutoScaling::UpdateAutoScalingGroup=HASH(0x61054d8)', 'Paws::Net::APIResponse=HASH(0x60f6430)') called at /opt/deployer/embedded/lib/perl5/site_perl/5.24.4/Paws/Net/Caller.pm line 46
Paws::Net::Caller::caller_to_response('Paws::Net::Caller=HASH(0x5e94fd8)', 'Moose::Meta::Class::__ANON__::SERIAL::16=HASH(0x5e998a0)', 'Paws::AutoScaling::UpdateAutoScalingGroup=HASH(0x61054d8)', 'Paws::Net::APIResponse=HASH(0x60f6430)') called at /opt/deployer/embedded/lib/perl5/site_perl/5.24.4/Paws/Net/RetryCallerRole.pm line 19
Paws::Net::RetryCallerRole::do_call('Paws::Net::Caller=HASH(0x5e94fd8)', 'Moose::Meta::Class::__ANON__::SERIAL::16=HASH(0x5e998a0)', 'Paws::AutoScaling::UpdateAutoScalingGroup=HASH(0x61054d8)') called at /opt/deployer/embedded/lib/perl5/site_perl/5.24.4/Paws/AutoScaling.pm line 285
Paws::AutoScaling::UpdateAutoScalingGroup('Moose::Meta::Class::__ANON__::SERIAL::16=HASH(0x5e998a0)', 'MaxSize', 10, 'HealthCheckGracePeriod', 600, 'VPCZoneIdentifier', 'subnet-30020f59,subnet-90017add', 'HealthCheckType', 'ELB', 'DesiredCapacity', 1, 'MixedInstancesPolicy', 'HASH(0x60a2778)', 'LaunchTemplate', 'HASH(0x5c4c3c8)', 'AutoScalingGroupName', 'ml_rest_services_active_autoscaling_group', 'MinSize', 1) called at lib/AutoScaling/Group.pm line 100
AutoScaling::Group::_createAutoScalingGroupByLt('AutoScaling::Group=HASH(0x4219590)', 'LoadBalancer', 'preprod-mrs-active-lb', 'DesiredCapacity', 1, 'HealthCheckType', 'ELB', 'Name', 'ml_rest_services_active_autoscaling_group', 'MaxSize', 10, 'HealthCheckPeriod', 600, 'MinSize', 1, 'vpcZoneIdentifier', 'subnet-30020f59,subnet-90017add', 'LaunchTemplate', 'HASH(0x5c4c3c8)', 'MixedInstancesPolicy', 'HASH(0x60a2778)') called at lib/AutoScaling/Group.pm line 67
AutoScaling::Group::createAutoScalingGroup(undef, 'HASH(0x5b53fa8)') called at lib/AutoScaling.pm line 171
AutoScaling::run('AutoScaling=HASH(0x4336d48)') called at bin/autoscale.pl line 15

**Comment by Prajithp** [comment]
Ii was my mistake :)
