### ISSUE TITLE
New AWS Service: Transit Gateway

### ISSUE THREAD

**Issue by scampbell123** [pplu/aws-sdk-perl#307]
Hi, just wondering if there will be support for the new Transit Gateway anytime soon?  I can test if needed!

Thank you,
Scott

**Comment by byterock** [comment]
Is that even a service available in the AWS CLI yet??

https://docs.aws.amazon.com/cli/latest/reference/#available-services?

I do not see it on the above list??

**Comment by scampbell123** [comment]
Ahh, in the CLI, I'm not sure.  I have a call with AWS shortly and can ask.  I am however using it from the AWS Console.  It's an option, just like VPNs/etc under the VPC settings.

 Security
    Network ACLs
    Security Groups

VPN Connections
    Customer Gateways
    Virtual Private Gateways
    VPN Connections

**Transit Gateways
    Transit Gateways
    Transit Gateway Attachments
    Transit Gateway Route Tables**

**Comment by scampbell123** [comment]
FYI, just found it under the EC2 service: https://docs.aws.amazon.com/cli/latest/reference/ec2/index.html.

**Comment by byterock** [comment]
I had a look at some codebase not sure if it is python yet
if only just got into Java a few days ago 

https://github.com/aws/aws-sdk-java/commit/8a1aaeef8f26372b1a3e0785d0f7ec9b9475997a#diff-2a4f4825c7c19eabef4b428762aae599

has to get into python boto3 first I think

The more expreiance PAWs guys might know

**Comment by pplu** [comment]
You should have it available in the release/0.39 branch (where all the development for the next release is happening)

**Comment by scampbell123** [comment]
Great thanks.

Sent from my iPhone

On Dec 7, 2018, at 3:53 AM, Jose Luis Martinez <notifications@github.com<mailto:notifications@github.com>> wrote:


You should have it available in the release/0.39 branch (where all the development for the next release is happening)

**Comment by pplu** [comment]
Released to CPAN with Paws 0.39
