### ISSUE TITLE
EKS and MQ query warning message: Use of uninitialized value in subroutine entry at Net/Amazon/Signature/V4.pm line 106

### ISSUE THREAD

**Issue by beginga** [pplu/aws-sdk-perl#325]
Hello,

API query again MQ and EKS is working fine, except that I get this error message (the standard output is correct):

my $mq = Paws->service('MQ',  region =>  $region) ;
my $result = $mq->ListBrokers ;
Use of uninitialized value in subroutine entry at /usr/local/share/perl5/Net/Amazon/Signature/V4.pm line 106.

 my $eks = Paws->service('EKS', region =>  $region );
my $result = $eks->ListClusters ;
Use of uninitialized value in subroutine entry at /usr/local/share/perl5/Net/Amazon/Signature/V4.pm line 106.

Regards,

Gautier

**Comment by pplu** [comment]
Hi,
   I suppose this has started happening once you have applied the patch to not send `{}` as the HTTP body, ¿right?

**Comment by beginga** [comment]
Yes, you get it

**Comment by beginga** [comment]
Hello,

I use the last version of the library and the error message is still present.

Regards

**Comment by pplu** [comment]
The warning should be solved when 0.41 is released

**Comment by pplu** [comment]
The Signature::V4 module doesn't like Paws passing undef as the HTTP content. It signs correctly, but perl spits out a warning about passing it undef.

Since the sha256 for undef and for '' is the same, we'll guarantee that the signer doesn't recieve undef
This script demonstrates this logic:
```
use strict;
use warnings;

use v5.10;
use Digest::SHA qw/sha256_hex/;
say sha256_hex('');
say sha256_hex(undef);
```

**Comment by pplu** [comment]
0.41 Just hit the CPAN with a fix for this issue. Thanks for your contribution.

**Comment by beginga** [comment]
Many thanks ;)
