### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by bit0mike** [pplu/aws-sdk-perl#331]
I'm attempting to write some code to automatically block/unblock IPs by modifying the network ACL entry on a VPC subnet.  The code I have that calls EC2 CreateNetworkAclEntry works fine for IPv4 but doesn't work for IPv6 because that uses Ipv6CidrBlock instead of CidrBlock, and there's no "Ipv6CidrBlock" Moose attribute on, well, pretty much anything.  Plus the CidrBlock one is marked as required, when it should be that one of the two is required but not both/neither)

Similarly, the EC2 DescribeNetworkAcls call only lists the v4 addresses in the list and ignores the v6 ones.

I haven't tried the security group code (mostly because you can't have Deny rules in security groups) but it doesn't seem to have the v6 attributes either.

All of this works fine in the AWS CLI tool.

**Comment by pplu** [comment]
Hi,

   Do you have the latest version of Paws? The IPv6 attributes should be there: https://metacpan.org/pod/Paws::EC2::NetworkAclEntry

**Comment by bit0mike** [comment]
Welp, I'm a complete and total idiot.  :)

Apparently the FreeBSD ports collection has a VERY old version: 0.14.  I'll go yell at them to update it.  Sorry for the unnecessary noise.

**Comment by pplu** [comment]
> Welp, I'm a complete and total idiot. :)

Please don't feel that way. Could happen to anyone.

> Apparently the FreeBSD ports collection has a VERY old version: 0.14. I'll go yell at them to update it. Sorry for the unnecessary noise.

At least now I know that FreeBSD ports has a very old version of Paws :laughing:, and that someone will try to get it updated :rofl: 

Thanks for reporting back
