### ISSUE TITLE
Release 0.41

### ISSUE THREAD

**Issue by drmmr763** [pplu/aws-sdk-perl#332]
Hi PAWS folks!

I am really interested in the Textract support that looks like it will be included in the 0.41 release (https://github.com/pplu/aws-sdk-perl/tree/release/0.41/auto-lib/Paws/Textract).

Is there an estimated release date for Release 0.41? What are the blockers for getting that release out? Can I help fix any issues? It looks like tests are failing right now for that branch in Travis. Who can I send some 🍻 to encourage this to happen?

**Comment by pplu** [comment]
Have you tried the code from release/0.41 to see if it works for you? Right now the tests aren't passing because of a problem generating `ApiGatewayV2`, but the rest should work correctly.

You can try to CPAN package the code on the release branch with
```
dzil build
```
and later installing the generated .tar.gz with
```
cpanm -n -l local /path/to/Paws-XXXX.tar.gz
```
Hope it helps while 0.41 isn't released :)

**Comment by drmmr763** [comment]
Hi @pplu  thanks for the info and the reply! 

I'm sure that the build process you're suggesting will work. I can test it out locally. Unfortunately, we have a whole dockerized build process and adding locally sourced packages to it isn't something we've had to do before and I think it'd be a lot of effort. 

Do you happen to have an estimated / planned release for .41 or an idea of what is holding it back? I'm trying to figure out if its worth it for us to try to wait for the release, or try to build our own wrapper code for the Textract service. 

Thanks for any insight you can provide!

**Comment by pplu** [comment]
Hi, 0.41 should be released this week

**Comment by drmmr763** [comment]
Awesome! That's great news thanks for the update.

**Comment by pplu** [comment]
0.41 Just hit the CPAN

**Comment by drmmr763** [comment]
Thanks so much for the updates. We are excited! thanks for all your hard work and efforts.
