### ISSUE TITLE
Depends on non-existent module Data::Path

### ISSUE THREAD

**Issue by eserte** [pplu/aws-sdk-perl#35]
Data::Path, specified as TEST_REQUIRES (see here https://metacpan.org/source/JLMARTIN/Paws-0.09/Makefile.PL#L50 ) is not available on CPAN. While installing with CPAN.pm:
```
...
Running test for module 'Data::Path'

  The module Data::Path isn't available on CPAN.
...
```

**Comment by pplu** [comment]
Ups! Have they pulled this module from CPAN? Has it maybe been renamed?

**Comment by pplu** [comment]
I can't find it in search.cpan.org and metacpan.org, but here it is http://search.cpan.org/~zaphar/Data-Path-1.4.1/. I understand that the lack of this module is preventing installation from CPAN for you. Right?

**Comment by pplu** [comment]
I've just pushed Paws 0.10 to CPAN that doesn't depend on Data::Path anymore for testing

Cheers, and thanks for the feedback!

**Comment by eserte** [comment]
Data::Path does not seem to be properly indexed. I reported this issue five years ago: https://rt.cpan.org/Ticket/Display.html?id=55483
