### ISSUE TITLE
DynamoDB Marshaler

### ISSUE THREAD

**Issue by dbaid** [pplu/aws-sdk-perl#360]
Hello,

Sorry to bother you, I am just asking for a help.

I am trying to use Paws::DynamoDB , but I find it's hard to serialize the response  output hashref structure. I am also try  Net::Amazon::DynamoDB::Marshaler to do the serialization jobs. But it seems not stable. Do you consider add a Paws native module for that ??

Here is my code :
```
use strict;
use warnings;
use Paws;
use v5.30;
use Data::Printer;
use Data::Dumper qw(Dumper);
use Net::Amazon::DynamoDB::Marshaler;
 my $table_name = 'Emails_7';

$ENV{'AWS_CONFIG_FILE'} = 'C:\Users\p10303550\.aws\credentials';
my $d = Paws->service('DynamoDB',region => 'us-east-2');
my $r;
 
$r = $d->Scan(TableName => $table_name);
my $r2=$r->Items->[0]->Map;
print Dumper $r2;

my $attrs = dynamodb_unmarshal($r2);
print Dumper $attrs;

for my $col (keys %$attrs) { say "$col : $attrs->{$col}";}
```

My test result:

------test1-------
```
$VAR1 = {
          'cnt' => bless( {
                            'N' => '45',
                            'L' => []
                          }, 'Paws::DynamoDB::AttributeValue' ),
          'email' => bless( {
                              'L' => [],
                              'S' => 'e2@test.com'
                            }, 'Paws::DynamoDB::AttributeValue' )
        };
$VAR1 = {
          'cnt' => '45',
          'email' => []
        };
cnt : 45
email : ARRAY(0x8ff9278)
```

------ test2------------
```
$VAR1 = {
          'cnt' => bless( {
                            'L' => [],
                            'N' => '45'
                          }, 'Paws::DynamoDB::AttributeValue' ),
          'email' => bless( {
                              'L' => [],
                              'S' => 'e2@test.com'
                            }, 'Paws::DynamoDB::AttributeValue' )
        };
$VAR1 = {
          'cnt' => [],
          'email' => []
        };
cnt : ARRAY(0x8d02950)
email : ARRAY(0x8d072a0)
```
---test3-----------------------------
```
$VAR1 = {
          'email' => bless( {
                              'S' => 'e2@test.com',
                              'L' => []
                            }, 'Paws::DynamoDB::AttributeValue' ),
          'cnt' => bless( {
                            'L' => [],
                            'N' => '45'
                          }, 'Paws::DynamoDB::AttributeValue' )
        };
$VAR1 = {
          'email' => 'e2@test.com',
          'cnt' => []
        };
email : e2@test.com
cnt : ARRAY(0x8ee8530)
```
------test4-----------------------
```
$VAR1 = {
          'email' => bless( {
                              'S' => 'e2@test.com',
                              'L' => []
                            }, 'Paws::DynamoDB::AttributeValue' ),
          'cnt' => bless( {
                            'N' => '45',
                            'L' => []
                          }, 'Paws::DynamoDB::AttributeValue' )
        };
$VAR1 = {
          'cnt' => '45',
          'email' => 'e2@test.com'
        };
cnt : 45
email : e2@test.com
```
 Good day!!
Steven

**Comment by pplu** [comment]
Hi, 

@stevecaldwell77 developed the module: https://metacpan.org/pod/PawsX::DynamoDB::DocumentClient that may help you for your tasks. He is also the author of Net::Amazon::DynamoDB::Marshaler, so maybe he can help out with the stability problem.

**Comment by stevecaldwell77** [comment]
NOTE: I fixed the bug above that @dbaid reported for `Net::Amazon::DynamoDB::Marshaler` here:

https://github.com/stevecaldwell77/Net-Amazon-DynamoDB-Marshaler/issues/1

**Comment by pplu** [comment]
@stevecaldwell77 : thanks!

@dbaid : Although we have #41, that was opened years ago, before @stevecaldwell77 started work on the DynamoDB Marshaler. For the moment I'd keep Paws behavior limited to the core DynamoDB behavior. If Paws would support this marshaling natively (proposals and patches welcome), it would probably use Steve's marshaller, so any work towards "stabilizing" it looks good. Also I'd like to know if there is any official marsalling / unmarshalling test suite for dynamodb documents that we could use to assure that the behaviour Paws implements is "standard".

I'd love to mention these related modules in the Paws docs, so that people know about possibilities without endless searching, but don't have that capability yet, since the docs are autogenerated from what AWS has in it's definitions.

**Comment by dbaid** [comment]
Hello,
 I tried another module -- MooseX-Storage-IO-AmazonDynamoDB-0.08.
I also just had a try using Net::Amazon::DynamoDB::Marshaler 0.07, and it works.
Thank you both @pplu and @stevecaldwell77.

Regards,
Steven
![test-MooseX-Storage-IO-AmazonDynamoDB-0 08](https://user-images.githubusercontent.com/47732154/69792049-c1dce280-1200-11ea-8f75-0aa5727b58a7.jpg)
![test-Net-test-Amazon-DynamoDB-Marshaler-0 07](https://user-images.githubusercontent.com/47732154/69792064-c903f080-1200-11ea-91f2-c3b1a13144ae.jpg)
