### ISSUE TITLE
Throw structured "NoRegionError"

### ISSUE THREAD

**Issue by pplu** [pplu/aws-sdk-perl#37]
NoRegionError is thrown as a string. Would be good to have a Paws::Exception object thrown

**Comment by Kharec** [comment]
Hi,

I'm just beginning to look at Paws code, but isn't it a Paws::Execption yet ? In /lib/Paws/API/EndpointResolver.pm : 

![image](https://cloud.githubusercontent.com/assets/796582/8715929/e2e7650c-2b89-11e5-9233-a20dfaec64ba.png)

I see a Paws::Exception thrown. Please tell me if I'm wrong.

**Comment by pplu** [comment]
Yes! I opened the issue some days ago, and pushed code that solves it yesterday night :). If you're interested in playing around, look at the readme on how to setup a dev environment (should be fast). I have some items that can be worked on that are not on GH yet, or if you have any special interest, just say, and I can guide you.

**Comment by Kharec** [comment]
Yep,

Already setted up a dev env, I'll take a look more deeply tonight, but your project sounds very fun :)

**Comment by pplu** [comment]
This is now in master, and will be pushed to CPAN in v0.13
