### ISSUE TITLE
Impossible to clear Stack Tags using AWS::CloudFormation::UpdateStack

### ISSUE THREAD

**Issue by torrentalle** [pplu/aws-sdk-perl#376]
I'm not able to clear CloudFormation Stack Tags using PAWS::CloudFormation::UpdateStack. As is  [mentioned in the documentation](https://metacpan.org/pod/Paws::CloudFormation::UpdateStack#Tags-=%3E-ArrayRef[Paws::CloudFormation::Tag])

> If you don't specify this parameter, AWS CloudFormation doesn't modify the stack's tags. If you specify an empty value, AWS CloudFormation removes all associated tags.

but when I try to execute this code, the Stack Tags **doesn't get cleared as expected**

```perl
                my $cfn = $aws->service('CloudFormation');           
		$cfn->UpdateStackStack(
                        Name => 'test-stack,
			Capabilities => [ 'CAPABILITY_IAM', 'CAPABILITY_NAMED_IAM', 'CAPABILITY_AUTO_EXPAND' ],
			UsePreviousTemplate => 1,
			Tags => [],
		);
```

If the parameter is an array, the Paws::Net::QueryCaller class only generates the query parameter when this parameter has elements.

https://github.com/pplu/aws-sdk-perl/blob/master/lib/Paws/Net/QueryCaller.pm#L36
```perl
[ ... ]
 } elsif ($att_type =~ m/^ArrayRef\[(.*)\]/) {
          if (Paws->is_internal_type("$1")){
            my $i = 1;
            foreach my $value (@{ $params->$att }){
              $p{ sprintf($self->array_flatten_string, $key, $i) } = $value;
              $i++
            }
          } else {
            my $i = 1;
            foreach my $value (@{ $params->$att }){
              my %complex_value = $self->_to_querycaller_params($value);
              map { $p{ sprintf($self->array_flatten_string . ".%s", $key, $i, $_) } = $complex_value{$_} } keys %complex_value;
              $i++
            }
          }
[ ... ]

**Comment by castaway** [comment]
Merged
