### ISSUE TITLE
LexRuntime POD malformed

### ISSUE THREAD

**Issue by pplu** [pplu/aws-sdk-perl#380]
I've had to manually ammend LexRuntime in 2596a566808d4cdd16a57d2daf3fe46f10337542. I haven't had time to investigate into why the POD is malformed, but I want the tests running correctly before 0.42 release (note: see https://travis-ci.org/pplu/aws-sdk-perl/jobs/654912390#L514 for failure)

**Comment by castaway** [comment]
Impressive, I'll add it to looking at for 0.43

**Comment by castaway** [comment]
Looks like one of the doc templates added some spaces before some html-to-pod gen, which ended up starting with "=over".. sorted.
