### ISSUE TITLE
CPAN thinks the most recent version is 0.41

### ISSUE THREAD

**Issue by dakkar** [pplu/aws-sdk-perl#390]
CPAN seems to have had problems indexing release 0.42, so `02packages.details.txt` thinks that the latest version of the `Paws` module is 0.41 (but it knows that the latest version of ~20k other
`Paws::*` modules is 0.42)

Could you try asking CPAN to re-index? I can't see why it got confused, but maybe re-indexing is enough.

**Comment by pplu** [comment]
I've just submitted the reindex. Just know that Paws takes some hours to reindex

**Comment by dakkar** [comment]
thank you! (also, not-very-related: your CPAN email address bounces, pobox doesn't seem to recognise your address)

**Comment by dakkar** [comment]
looks like it worked! thank you again
