### ISSUE TITLE
Present Sate?

### ISSUE THREAD

**Issue by byterock** [pplu/aws-sdk-perl#395]
Getting back to Paws again and would like to know what the presents state of things are.

Are the devs at shadow-cat working on anything?

Is  there going to be a 0.43 release????

Would like to get all the patches I did merged in and up to CPAN as I have some time these days to play with this.

Cheers
John

**Comment by byterock** [comment]
Still waiting on this one!!.  Would love to get Paws all cleaned up.

**Comment by shogo82148** [comment]
ping

@pplu I'm waiting too.
or if you don't enough time about this, may I help you with releasing?

**Comment by byterock** [comment]
So what needs to get done for 0,43?  Just the release?

**Comment by castaway** [comment]
As far as I remember, yes - testing (of the actual tarball) and release..

**Comment by pplu** [comment]
Hi,

   Sorry for the late response, as I'm currently not able to contribute much to Paws right now, and it seems like the work that @castaway was doing was truncated by the pandemic.

   @byterock if you're up for releasing Paws, I can give you CPAN comaint so you can release versions. I think that after releasing the tarball, the next was merging your changes in, so I think that would be an easy task. If you need some help I can also try to assist getting you to know how to release Paws.

Best Regards,

Pplu

**Comment by byterock** [comment]
Hi Jose

Yes I will have some time for that.  I can at least give it a try.  [https://github.com/shogo82148](shogo82148) also is willing to help out.

I have done the odd little release to cpan so some-what familiar with the process.  Will need you step-by-step recipe so I can get it right.

I think you have my personal email someplace and I am on cpan as well.

Cheers John

**Comment by pplu** [comment]
@byterock you now have COMAINT in CPAN. Releasing was documented here: https://github.com/pplu/aws-sdk-perl#releasing

**Comment by byterock** [comment]
great will try to get things in order shortly.  Might do a small limited release first just to test things out.

**Comment by Prajithp** [comment]
@pplu  is this completely stopped?

**Comment by byterock** [comment]
Well not 100% got side-tracked with some critical work related issues.  I hope to get some time to play with PAWS at least one day a week this year.

Today I am trying to set up a new Linux box that I can use to create the new release.  My last attempt back in November was unsuccessful and only getting back to it now.

**Comment by Prajithp** [comment]
Thanks @byterock  Most of our deployment pipelines are depending on Paws, so that's why I just asked here.

**Comment by byterock** [comment]
Jose

I finally had some time to play with Paws again  and tried to do a release of 0.43 today

I get stuck when I try to push back to github

git push origin release/0.43
Username for 'https://github.com': byterock@hotmail.com
Password for 'https://byterock@hotmail.com@github.com':
remote: Permission to pplu/aws-sdk-perl.git denied to byterock.
fatal: unable to access 'https://github.com/pplu/aws-sdk-perl.git/': The requested URL returned error: 403

Not 100% sure what to do here??

I can do a 'make dist'  but I do not really want to stick that on CPAN if I did not follow all the proper release steps.

My guess I need more permissions on github??   to merge and tag to master??

Cheers
John

**Comment by Prajithp** [comment]
@pplu Can you please check?

**Comment by pplu** [comment]
@byterock @Prajithp Sorry for the delay! I didn't get the notification from GitHub.

@byterock : you should now be able to push to GitHub

**Comment by byterock** [comment]
Ok thanks will have to start ramping up again.  Will try to check on it later today

Cheers

**Comment by msven** [comment]
Any updates @byterock?

**Comment by byterock** [comment]
Sorry been swamped with other work projects.    I will 100% try to get something by the end of the week

**Comment by byterock** [comment]
PPU been trying out a release but this time suck when I go to do a
make dist
 I keep getting a 
Can't locate App/Cmd/Setup.pm 

on 

cpanm -n -l dzil-local Dist::Zilla

any advice??

**Comment by pplu** [comment]
@byterock : seems like something to do with the toolchain / your Perl setup, since this step is trying to get Dist::Zilla installed in a local dzil-local/ directory.

You can always try to delete dzil-local (since it will get regerenerated) on the next `make dist`.

**Comment by byterock** [comment]
yep tried that 
will try on a separate box with a clean tool chain

**Comment by pplu** [comment]
@byterock : did you have any luck? I tried, out of curiosity, to `make dist` a newly cloned 0.43 branch, and it worked flawlesly.

**Comment by byterock** [comment]
Ping fainlly back at it

I fixed the perl chain so I get the make dist  to work now (local perl path issue)

I can't seem to generate the correct 0.43 tar.gz file I keep getting 0.42
Am  I  missing a step to update the  version someplace?  
Cheers
John

**Comment by byterock** [comment]
opps never mind I found it later down the page. A case of  RTFIF on my part

**Comment by byterock** [comment]
Well  few goofs today but progress hopefully I can do the 0.43 release today

**Comment by pplu** [comment]
@byterock Just saw 0.43 hit CPAN :)

```
████░██░██░░▄███▄░░██▄░██░██░▄██
░██░░██▄██░██▀░▀██░███▄██░████▀░
░██░░██▀██░███████░██▀███░████▄░
░██░░██░██░██░░░██░██░░██░██░▀██

██▄░░▄██░░▄███▄░░██░░██░░
░▀████▀░░██▀░▀██░██░░██░░
░░░██░░░░██▄░▄██░██░░██░░
░░░██░░░░░▀███▀░░▀████▀░░


██░░░██░████░████▄░██▄░░▄██░░
██▄░▄██░██▄░░██░██░░▀████▀░░░
░██▄██░░██▀░░████▀░░░░██░░░░░
░░███░░░████░██░██░░░░██░░░░░

██▄░▄██░██░░██░░▄███▄░██░██
██▀█▀██░██░░██░██▀░▀▀░██▄██
██░░░██░██░░██░██▄░▄▄░██▀██
██░░░██░▀████▀░░▀███▀░██░██
```

**Comment by byterock** [comment]
Lets hope I did not muck it up too much

Will have to a bug fix first then get all that other work I have done what a year ago  or was it two up on CPan

**Comment by byterock** [comment]
Ok I put it on man PAUSE account how does it got published into PAWS?  I though that was automatic once I had permission??

**Comment by pplu** [comment]
Closing because 0.43 is released

**Comment by byterock** [comment]
I still haven't seen it on CPAN?  Did I miss something on the relase??

**Comment by byterock** [comment]
Ah something is not right it is under my user ID and does not look complete.

https://metacpan.org/release/BYTEROCK/Paws-0.43

Can you have a look we might have to adjust something??

**Comment by pplu** [comment]
I see everything OK. It takes a good while for PAUSE and metacpan to index it!
