### ISSUE TITLE
Shouldn't 'dir' be 'path'?

### ISSUE THREAD

**Issue by Skeeve** [pplu/aws-sdk-perl#401]
https://github.com/pplu/aws-sdk-perl/blob/95db4ae45612d9e9760bc15188d56bf59e7f5a8f/lib/Paws/Credential/File.pm#L104

I think it should be "path", not "dir" used in the example.

**Comment by pplu** [comment]
Sure looks so :). A pull request with a doc patch, and any other stuff you see fit (since I see you're trying stuff out) would be gratefully accepted.

**Comment by pplu** [comment]
3555f2d6772ba9d0db2501ab3401c83de24e3eb9 fixes this. Will be shipped in 0.44
