### ISSUE TITLE
dependency Archive::Any::Lite is failing

### ISSUE THREAD

**Issue by becryan** [pplu/aws-sdk-perl#407]
When running command in docker container to build this module , am continuously running into failure at the following: -- truncated transfer for Archive:Any::Lite 0.06

```
  ISHIGAKI/Module-CPANTS-Analyse-1.01.tar.gz
  /usr/bin/perl Makefile.PL INSTALLDIRS=site -- OK
Running make for I/IS/ISHIGAKI/Module-CPANTS-Analyse-1.01.tar.gz
----  Unsatisfied dependencies detected during  ----
---- ISHIGAKI/Module-CPANTS-Analyse-1.01.tar.gz ----
    Archive::Any::Lite [requires]
    Array::Diff [requires]
    CPAN::DistnameInfo [requires]
    Data::Binary [requires]
    File::Find::Object [requires]
    Perl::PrereqScanner::NotQuiteLite [requires]
    Software::License [requires]
Running install for module 'Archive::Any::Lite'
Checksum for /root/.cpan/sources/authors/id/I/IS/ISHIGAKI/Archive-Any-Lite-0.11.tar.gz ok
Configuring I/IS/ISHIGAKI/Archive-Any-Lite-0.11.tar.gz with Makefile.PL
Checking if your kit is complete...
Looks good
Warning: prerequisite Archive::Zip 0 not found.
Warning: prerequisite Test::UseAllModules 0.10 not found.
Generating a Unix-style Makefile
Writing Makefile for Archive::Any::Lite
Writing MYMETA.yml and MYMETA.json
  ISHIGAKI/Archive-Any-Lite-0.11.tar.gz
  /usr/bin/perl Makefile.PL INSTALLDIRS=site -- OK
Running make for I/IS/ISHIGAKI/Archive-Any-Lite-0.11.tar.gz
---- Unsatisfied dependencies detected during ----
----   ISHIGAKI/Archive-Any-Lite-0.11.tar.gz  ----
    Archive::Zip [requires]
    Test::UseAllModules [build_requires]
Running install for module 'Archive::Zip'
CPAN: LWP::UserAgent loaded ok (v6.31)
Fetching with LWP:
http://www.cpan.org/authors/id/P/PH/PHRED/Archive-Zip-1.68.tar.gz
Transfer truncated: only 64967 out of 163490 bytes received
```

**Comment by pplu** [comment]
I've built Paws in containers before with out problems.

Can you share relevant parts of your Dockerfile? (base, OS packages being installed, how CPAN deps are being installed...) so I can try to reproduce?

**Comment by becryan** [comment]
Hi Jose, thanks for your speedy response.
It seems we had this outage for 4 days, and literally got it to build again with no problems and no changes. 

in that interim 4 days i succesfully built by using wget on the tar file and running the build commands.

with regard to the docker container when it was failing, predeeding lines were:
``
FROM ubuntu:bioinic

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get install -y \
    build-essential git cmake \
    libboost-all-dev \
    libeigen3-dev \
    libarmadillo-dev \
    liblas-dev liblas-c-dev \
    libpcl-dev \
    liblz4-dev
# General perl packages
RUN apt-get update
RUN apt-get install -y \
        liblog-log4perl-perl \
        libdbi-perl \
        libdbd-pg-perl \
        libnet-address-ip-local-perl \
        libnet-stomp-perl \
        libproc-background-perl \
        libdata-guid-perl \
        libpdal-dev \
        pdal \
        liblas-bin

# Dependencies for Consul::Simple
RUN apt-get update
RUN apt-get install -y \
        libhttp-date-perl \
        libjson-perl \
        libwww-perl \
        liblwp-useragent-chicaching-perl

RUN cpan Consul::Simple Paws
``

**Comment by pplu** [comment]
Looks like this was a transient failure.
