### ISSUE TITLE
use of direct $ENV{HOME} is not architecturally sensitive

### ISSUE THREAD

**Issue by karenetheridge** [pplu/aws-sdk-perl#52]
Paws::Credential::File uses $ENV{HOME} directly in code -- this is better replaced with File::HomeDir, which understands architectures where this environment variable is not defined, and uses additional fallback measures.

**Comment by pplu** [comment]
Hi!

Thanks for the report. I found that module shortly ago, and wanted to put it in :)

**Comment by pplu** [comment]
Scheduled for next release to CPAN. I'll close the issue when it hits CPAN

**Comment by pplu** [comment]
Released to CPAN :smile:

**Comment by karenetheridge** [comment]
Awesome, thank you very much!
