### ISSUE TITLE
DynamoDb Scan returns empty data objects

### ISSUE THREAD

**Issue by stevecaldwell77** [pplu/aws-sdk-perl#56]
Given that you have a DynamoDb table named 'foo' with a few items, in us-east-1, running this:

```
my $dyndb= Paws->service('DynamoDB', region => 'us-east-1');
my $response = $dyndb->Scan(TableName => 'foo');
my $item = $response->Items->[0];
die unless defined $item->Map;
```

will die on that last line.  From a few minutes digging around in the source, it seems that Paws::API::Caller::new_from_struct() isn't handling a HashRef[Paws::DynamoDB::AttributeValue] correctly.

**Comment by pplu** [comment]
Hi! Thanks for the report! I'm looking to fix it. Sorry for the long response time (been on vacation)

**Comment by pplu** [comment]
Hi! I've pushed a version that should fix your issue, and added tests to avoid regressions. Can you test it out?

**Comment by stevecaldwell77** [comment]
Works great!  Although now I see a need for a Paws::DynamoDB::AttributeValue => Perl hashref mapper :)

**Comment by pplu** [comment]
Do you mean #41? It's up for the taking! If you need help just yell
