### ISSUE TITLE
Coercion issue with DynamoDB::BatchWriteItem and RequestItems argument.

### ISSUE THREAD

**Issue by bluefeet** [pplu/aws-sdk-perl#80]
This:

```
$ddb->BatchWriteItem(
  RequestItems=>{$table_name=>[{PutRequest=>{Item=>{pagekey => {S=>'ho'},
                                                   job_count =>{N=>'123'},
                                                    drilldown =>{S=>'hello'}}}}]}
    );
```

Throws this:

```
Attribute (Map) does not pass the type constraint because: Validation failed for 'HashRef[ArrayRef[Paws::DynamoDB::WriteRequest]]' with value { phony_jds: [ HASH(0x53ad0b8) ] }
```

Looks to me like there is a missing coercion from a hash ref to a Paws::DynamoDB::WriteRequest object.

I expect the fix is something similar to d134cbf.

**Comment by pplu** [comment]
Hi! I'm working on it :)

The fix isn't as trivial as the last one, though, because there are HashRef[ArrayRef[OBJECT]] and HashRef[ArrayRef[Str]] to handle in the API, and the fix also may have to do with how the code is generated for these types of maps.

**Comment by pplu** [comment]
I've been working on it, and have this: https://github.com/pplu/aws-sdk-perl/tree/issue-80. Can you try out the code in this branch?

`HashRef[ArrayRef[OBJECT]]` objects are only used in DynamoDB, specifically in Batch calls, so they weren't tested. Now we have tests for when these types of objects form part of the input parameters to a request, but I've detected that BatchGetResponseMap follows the same pattern for outputs.

Can you please capture the return for the `BatchGetItem` call with 
```
paws_make_testcase DynamoDB --region xxx BatchGetItem ...
```
I suspect that the contents of the response will probably make Paws throw an error

**Comment by pplu** [comment]
JFYI: I'm working on some more problems with the DynamoDB Batch APIs. BatchGetItem isn't sane either... so I'm working on the issue-80 branch to get it all fixed

**Comment by bluefeet** [comment]
I've re-run my original test on the issue-80 branch (which I rebased onto master just in case) and get this error when I call BatchWriteItem now:

`'ArrayRef[Paws::DynamoDB::WriteRequest]' is not a module name`

I'll run the `paws_make_testcase` command you wanted me to run above next.

**Comment by bluefeet** [comment]
So, what's that syntax for using `paws_make_testcase`?  I don't see any docs anywhere for it, and my rudimentary attempts at passing BatchGetItem arguments to it are failing.

**Comment by bluefeet** [comment]
I just tried BatchGetItem and am getting a seemingly-coercion related error on the request:

```
Attribute (Map) does not pass the type constraint because: Validation failed for 'HashRef[ArrayRef[Paws::DynamoDB::AttributeMap]]' with value { phony_jds: [ HASH(0x51f69f8) ] } at /usr/local/lib/perl/5.14.2/Moose/Object.pm line 24
	Moose::Object::new('Paws::DynamoDB::BatchGetResponseMap', 'Map', 'HASH(0x51a7af0)') called at /home/aran/local-lib/lib/perl5/Paws/Net/JsonResponse.pm line 54
	Paws::Net::JsonResponse::handle_response_strtonativemap('Paws::DynamoDB=HASH(0x4b00128)', 'Paws::DynamoDB::BatchGetResponseMap', 'HASH(0x51a7af0)') called at /home/aran/local-lib/lib/perl5/Paws/API/Caller.pm line 182
	Paws::API::Caller::new_from_struct('Paws::DynamoDB=HASH(0x4b00128)', 'Paws::DynamoDB::BatchGetItemOutput', 'HASH(0x51c4998)') called at /home/aran/local-lib/lib/perl5/Paws/API/Caller.pm line 147
	Paws::API::Caller::response_to_object('Paws::DynamoDB=HASH(0x4b00128)', 'HASH(0x51c4998)', 'Paws::DynamoDB::BatchGetItem=HASH(0x51ab5a8)', 200, '{"Responses":{"phony_jds":[{"email":{"S":"foo@bar.com"}}]},"UnprocessedKeys":{}}', 'HASH(0x51faad0)') called at /home/aran/local-lib/lib/perl5/Paws/API/Caller.pm line 124
	Paws::API::Caller::handle_response('Paws::DynamoDB=HASH(0x4b00128)', 'Paws::DynamoDB::BatchGetItem=HASH(0x51ab5a8)', 200, '{"Responses":{"phony_jds":[{"email":{"S":"foo@bar.com"}}]},"UnprocessedKeys":{}}', 'HASH(0x51faad0)') called at /home/aran/local-lib/lib/perl5/Paws/Net/Caller.pm line 40
	Paws::Net::Caller::caller_to_response('Paws::Net::Caller=HASH(0x4b6d640)', 'Paws::DynamoDB=HASH(0x4b00128)', 'Paws::DynamoDB::BatchGetItem=HASH(0x51ab5a8)', 200, '{"Responses":{"phony_jds":[{"email":{"S":"foo@bar.com"}}]},"UnprocessedKeys":{}}', 'HASH(0x51faad0)') called at /home/aran/local-lib/lib/perl5/Paws/Net/Caller.pm line 32
	Paws::Net::Caller::send_request('Paws::Net::Caller=HASH(0x4b6d640)', 'Paws::DynamoDB=HASH(0x4b00128)', 'Paws::DynamoDB::BatchGetItem=HASH(0x51ab5a8)') called at /home/aran/local-lib/lib/perl5/Paws/Net/RetryCallerRole.pm line 18
	Paws::Net::RetryCallerRole::do_call('Paws::Net::Caller=HASH(0x4b6d640)', 'Paws::DynamoDB=HASH(0x4b00128)', 'Paws::DynamoDB::BatchGetItem=HASH(0x51ab5a8)') called at /home/aran/local-lib/lib/perl5/Paws/DynamoDB.pm line 46
	Paws::DynamoDB::BatchGetItem('Paws::DynamoDB=HASH(0x4b00128)', 'RequestItems', 'HASH(0x5132c50)') called at test_batch.pl line 43
```

**Comment by pplu** [comment]
Hey! Sorry for the delay... I'll be very busy till end of this week (when the first thing I'll do is put my hands into solving these issues).
If you want to take a shot: the GetBatchItem bug is in new_from_struct. It wasn't expecting that there could be HashRefs of ArrayRefs... so doesn't handle that very gracefully.

If I don't remember incorrectly, the BatchGetItem problem was divided in two:
Handling the BatchGetItem parameters, that are solved and tested here: https://github.com/pplu/aws-sdk-perl/blob/issue-80/t/05_service_calls.t#L347 and the "new_from_struct" bug.

**Comment by pplu** [comment]
Hi,

On branch https://github.com/pplu/aws-sdk-perl/tree/issue-80 BatchGetItem is now working correctly :dancer: 

Can you test out your use cases to see if everything is OK? I'm going to wait a couple of days for your feedback before pushing this to CPAN.

Thanks for your patience.
