### ISSUE TITLE
Lacking Documentation

### ISSUE THREAD

**Issue by frioux** [pplu/aws-sdk-perl#83]
Some of the documentation seems like it could be improved a lot.  For example https://metacpan.org/pod/Paws::CloudWatch::GetMetricStatistics#REQUIRED-EndTime-Str doesn't say what format the string should be, or give any examples.

As a side note, the POD on that page (and likely others) is generally weird, because the descriptions are rendered as preformatted text.

**Comment by pplu** [comment]
Hi! Thanks for the feedback. 

In master, pending to push to CPAN soon, the POD has been corrected. If you can checkout master with a POD browser to see if everything is OK, it would be of help.

The date format for cloudwatch is iso8601 (in examples you have a cw.pl script that exercises a bit of cloudwatch. There we pass DateTime->now->iso8601 to the timestamp fields. There is space for improvement in this field, as I would like to make Paws coerce DateTime values into the appropiate format for AWS APIs (I've heard there is some inconsitencies in the formats that each services dates are expected (help on exploring which API expects which format would be very well recieved).

Thanks!

**Comment by pplu** [comment]
JFYI: I've pushed a version to CPAN (0.23) with better documentation where the descriptions are not rendered with preformatted text.

I'll close this ticket, and open an issue that requests datetime handling
