### ISSUE TITLE
Add links to AWS docs

### ISSUE THREAD

**Issue by frioux** [pplu/aws-sdk-perl#84]
It would be super helpful if all of the docs linked to the related docs that amazon publishes.  Like for example, if https://metacpan.org/pod/Paws::CloudWatch#DeleteAlarms-AlarmNames-ArrayRef-Str (and https://metacpan.org/pod/Paws::CloudWatch::DeleteAlarms) linked to http://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_DeleteAlarms.html

**Comment by pplu** [comment]
Great Idea!

I'll explore if the links can be consistently generated for all services (at least for CloudWatch it looks feasable)

**Comment by castaway** [comment]
I'm being sponsored by ZipRecruiter to have a go at improving some of the Paws generated documentation. This is one of the items on my list.

I'd like to start with adding a link to the toplevel documentation, eg https://aws.amazon.com/documentation/s3/, https://aws.amazon.com/documentation/greengrass/, in the service class docs, as these do seem to have consistent naming.

This should be a straight forward update to the service class template, I was thinking of adding an attribute in the Paws::API::Builder class to hold the link, we could add a LWP check to verify that it doesn't 404, then insert the link into the template if its all fine.

**Comment by pplu** [comment]
Closing, as this was part of release 0.37. https://metacpan.org/changes/distribution/Paws#L10
