### ISSUE TITLE
S3::ListObjects Prefix doesn't work

### ISSUE THREAD

**Issue by e-tip** [pplu/aws-sdk-perl#86]
Hi,
If i use the Prefix param in the S3::ListObjects method i get the full content of the bucket.

`my $objects = $s3->ListObjects( Bucket => $bucket, Prefix => "e/e8/e82/e820c1941a11a7910d327ed07c0d7c8dc06696ee5d9d9278f7735c298287dc5c");
	foreach my $file ( @{ $objects->{Contents} }) {
		my $key = $file->{Key};
		print $key."\n";}`
i get this 

> d/df/df7/df73bec39362bb141383cc3ee24bc128a2d613de53d1089a27309ac59c2cf9c0/svg/jYm2gXgEB.svg
d/df/df7/df73bec39362bb141383cc3ee24bc128a2d613de53d1089a27309ac59c2cf9c0/svg/pEW2NXNRl.svg
d/df/df7/df73bec39362bb141383cc3ee24bc128a2d613de53d1089a27309ac59c2cf9c0/svg/qxb20X0jW.svg
d/df/df7/df73bec39362bb141383cc3ee24bc128a2d613de53d1089a27309ac59c2cf9c0/svg/xEqoYGYJm.svg
e/e8/e82/e820c1941a11a7910d327ed07c0d7c8dc06696ee5d9d9278f7735c298287dc5c/book.txt
e/e8/e82/e820c1941a11a7910d327ed07c0d7c8dc06696ee5d9d9278f7735c298287dc5c/svg/0jgPJz41m.svg
e/e8/e82/e820c1941a11a7910d327ed07c0d7c8dc06696ee5d9d9278f7735c298287dc5c/svg/2ZWevQ4YX.svg

**Comment by pplu** [comment]
Hi! Thanks for the report!

**Comment by pplu** [comment]
I've fixed the problem in master. Prefix, MaxKeys, etc are working correctly.

If you can, please confirm it works for you. I'll release to CPAN soon

**Comment by e-tip** [comment]
thanks, i'm going to check in next hours

**Comment by pplu** [comment]
Hi,

JFYI, I pushed the code that fixes this to CPAN
