### ISSUE TITLE
Furl required for testing, not declared

### ISSUE THREAD

**Issue by andk** [pplu/aws-sdk-perl#93]
As per subject. Sample fail reports listed on

http://analysis.cpantesters.org/reports_by_field?distv=Paws-0.22;field=qr%3A%28Can%27t%20locate%20\S%2Bpm%29

In case the above does not work anymore, an examples:

http://www.cpantesters.org/cpan/report/66773976

HTH&&Thanks,

**Comment by pplu** [comment]
Thanks for the report. I'll try to fix and push to CPAN as soon as I can :)

**Comment by pplu** [comment]
Hi! Just pushed to CPAN a version (0.23) that doesn't need Furl, even for testing (it's really an optional dep that is required for devel, or if you have Furl installed).

Thanks for the report
