### ISSUE TITLE
Paws::CloudWatch::PutMetricData  Parameter requirements incorrect

### ISSUE THREAD

**Issue by kg4242** [pplu/aws-sdk-perl#97]
In trying to use Paws::CloudWatch::PutMetricData  to send a metric to CW, the parameter list documentation says it needs an arrayRef (not HASHREF), and a scalar (String):

REQUIRED MetricData => ArrayRef[Paws::CloudWatch::MetricDatum]
REQUIRED Namespace => Str

Digging into Paws::CloudWatch::MetricDatum, we see that this is composed of the following:

Dimensions => ArrayRef[Paws::CloudWatch::Dimension]
REQUIRED MetricName => Str
StatisticValues => Paws::CloudWatch::StatisticSet
Timestamp => Str
Unit => Str
Value => Num

The bug/feature now shows up where we are asked to supply Paws::CloudWatch::StatisticSet in a call to PUT metrics, not GET them.  The Paws::CloudWatch::StatisticSet comprises:

REQUIRED Maximum => Num
REQUIRED Minimum => Num
REQUIRED SampleCount => Num
REQUIRED Sum => Num

This does not make any sense in a PutMetricData context, only in retrieving.  So the parameter type checking croaks in places and then dies when figuring up this call (which omits the StatisticSet):

$result = $cw->PutMetricData(
  Dimensions => [
    { Name => $dimension, Value => $dimension },
  ],
  MetricName => $metricName,
  Timestamp => "$stamp",
  Unit => 'Count',
  Value => 42,
  Namespace => $nameSpace
  );

Debugger gives:
========================
  DB<4> x $attr_name
0  'Value'
  DB<5> print  $meta->has_attribute($attr_name);

  DB<6> n
Class::MOP::Class::find_attribute_by_name(/usr/local/lib64/perl5/Class/MOP/Class.pm:926):
926:            my $meta = Class::MOP::Class->initialize($class);
  DB<6> 
Class::MOP::Class::find_attribute_by_name(/usr/local/lib64/perl5/Class/MOP/Class.pm:927):
927:            return $meta->get_attribute($attr_name)
928:                if $meta->has_attribute($attr_name);
  DB<6> 
Class::MOP::Class::find_attribute_by_name(/usr/local/lib64/perl5/Class/MOP/Class.pm:931):
931:        return;
  DB<6> 
Paws::API::Caller::new_with_coercions(/usr/local/share/perl5/Paws/API/Caller.pm:36):
36:             croak "$class doesn't have an $att" if (not defined $att_meta);
  DB<6> 
Paws::CloudWatch::PutMetricData doesn't have an Value at /usr/local/share/perl5/Paws/CloudWatch.pm line 63.
 at /usr/local/share/perl5/Paws/API/Caller.pm line 36.
        Paws::API::Caller::new_with_coercions('Paws::CloudWatch=HASH(0x5136648)', 'Paws::CloudWatch::PutMetricData', 'Dimensions', 'ARRAY(0x4ec40a8)', 'MetricName', 'ErrorCounts', 'Timestamp', 1462369168, 'Unit', ...) called at /usr/local/share/perl5/Paws/CloudWatch.pm line 63
        Paws::CloudWatch::PutMetricData('Paws::CloudWatch=HASH(0x5136648)', 'Dimensions', 'ARRAY(0x4ec40a8)', 'MetricName', 'ErrorCounts', 'Timestamp', 1462369168, 'Unit', 'Count', ...) called at pawsCwPutmetric.pl line 56
Debugged program terminated.  Use q to quit or R to restart,
  use o inhibit_exit to avoid stopping after program termination,
  h q, h R or h o to get additional info.  
  DB<6>

**Comment by pplu** [comment]
Hi!

It looks like you're missing the MetricData array of "MetricDatum". This works for me:
```
$result = $cw->PutMetricData(
  MetricData => [
    {
      Dimensions => [
        { Name => $dimension_name, Value => $dimension_value },
      ],
      MetricName => $metricName,
      Timestamp => $stamp,
      Unit => 'Count',
      Value => 42,
    }
  ],
  Namespace => $nameSpace
);
```
I think this will solve your issue. I'm open to listening if you have suggestions to docs / code that help avoid these types of errors :)

Thanks for your report,

Pplu

**Comment by pplu** [comment]
Did this help?

**Comment by pplu** [comment]
I'm closing this issue, as it looks like it was misinvocation of the method (missing the MetricData parameter)
