### ISSUE TITLE
Write to 2 SQS queues owned by 2 separate entities

### ISSUE THREAD

**Issue by rob0101** [pplu/aws-sdk-perl#98]
I'd like to write to two separate SQS queues that are owned by 2 separate entities.
Here's a simplified version of the code I tried, which doesn't work..

	$ENV{AWS_ACCESS_KEY} = $K1;
	$ENV{AWS_SECRET_ACCESS_KEY} = $K2;

	my $sqs_result = eval { 
		$service1 = Paws->service('SQS', region => 'ap-southeast-2');
	};

 	$ENV{AWS_ACCESS_KEY} = $K3;
	$ENV{AWS_SECRET_ACCESS_KEY} = $K4;

	my $sqs_result = eval { 
		$service2 = Paws->service('SQS', region => 'ap-southeast-2');
	};

The queue at service1   will always work.  service2 never works.

Is there a simple way to make this work ?.  I have minimal understanding of stuff on the AWS side.

thanks,
rob

**Comment by pplu** [comment]
Hi,

You can do something like this:
```
use Paws::Credential::Environment;
my $paws1 = Paws->new(
  config => {
    credentials => Paws::Credential::Environment->new(
      access_key => $ak1,
      secret_key => $sk1
    )
  }
);
$sqs1 = $paws1->service('SQS', region => 'ap-southeast-2');
# rinse and repeat to obtain $sqs2
```

Please take this into account: It's not a good practice to burn your credentials into your code. If you have them in "credentials" files, you can:
```
use Paws::Credential::File;
my $paws1 = Paws->new(
  config => {
    credentials => Paws::Credential::File->new(
      credentials_file => 'path_to_credfile',
      profile => 'account1',
    )
  }
);
$sqs1 = $paws1->service('SQS', region => 'ap-southeast-2');
# rinse and repeat to obtain $sqs2
```

The credentials file can have this format:
```
[account1]
aws_access_key_id=AKIXXXXXXXXXXXXXXXX
aws_secret_access_key=XXXXXXXXX

[account2]
aws_access_key_id=AKIYYYYYYYYYYYY
aws_secret_access_key=YYYYYYY
```

If you have the account credentials in some "strange" place, you can write a credentials class. Details are here: https://metacpan.org/pod/Paws#Credential-Provider-Pluggability, and then use it as follows:

```
use MyPawsCredProvider;
my $paws1 = Paws->new(
  config => {
    credentials => MyPawsCredProvider->new(
      for_account => 'account1',
    )
  }
);
$sqs1 = $paws1->service('SQS', region => 'ap-southeast-2');
# rinse and repeat to obtain $sqs2
```

Hope it helps :smile:

**Comment by rob0101** [comment]
Thanks!
I will give that a go.
